### ISSUE TITLE
Add slides with scikit-learn API 

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#109]
Probably to add somewhere in the Predictive Modelling Pipeline. 

http://ogrisel.github.io/decks/2019_intro_sklearn/#30
![image](https://user-images.githubusercontent.com/1680079/100319089-63874300-2fbf-11eb-94eb-1571d8ad4c73.png)

**Comment by GaelVaroquaux** [comment]
Good idea!

**Comment by lesteve** [comment]
I think this has been addressed through diagrams like 
![image](https://user-images.githubusercontent.com/1680079/115688988-f0aaaa00-a35b-11eb-8fb6-4c3f2aee4657.png)
