### ISSUE TITLE
Fix header warning

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#112]
in /home/lesteve/dev/scikit-learn-mooc/jupyter-book/python_scripts/linear_regression_non_linear_link.py
```
WARNING: Non-consecutive header level increase; 0 to 3
```

Probably this happened after splitting the notebook.

**Comment by glemaitre** [comment]
Thanks I will take care about it.

**Comment by glemaitre** [comment]
Thanks
