### ISSUE TITLE
UTF8 marker for exercise and solution

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#116]
The UTF8 markers in the titles help readability. We should add some for the exercise and their solutions.

**Comment by lesteve** [comment]
I propose 📝 for exercise and 📃 for solution

Firefox:
![image](https://user-images.githubusercontent.com/1680079/100632305-f95aff00-332c-11eb-9173-a0732b417594.png)

Chromium:
![image](https://user-images.githubusercontent.com/1680079/100632249-e8aa8900-332c-11eb-9d1f-6385942d81e2.png)

Alternative solution more than welcome:
https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by GaelVaroquaux** [comment]
I love your proposal. Thank you!

**Comment by lesteve** [comment]
There was also 🔓 but to me it is not clear enough that the lock is unlocked (on Firefox) ...
