### ISSUE TITLE
matplotlibrc to avoid "sns.set_context("talk")"

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#138]
In some notebooks, we have
```
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_context("talk")
```
(see https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_ex_02.html )

This crowds the notebook and makes it harder to understand, but there is clear value to the legibility.

Could we have a matplotlibrc file that does the same thing and that's only executed for the notebooks (not the slides)?

**Comment by glemaitre** [comment]
Yep, I introduce it to avoid additional font settings and hiding it completely could be really cool. As a side note, I added a note at the first occurrence (https://inria.github.io/scikit-learn-mooc/python_scripts/01_tabular_data_exploration.html#visual-inspection-of-the-data) when I introduced it.

NB: In terms of distraction, I would place it at the same level as the `random_state`.
NB2: I usually teach about this functionality when covering the plotting.
