### ISSUE TITLE
Consider adding notebooks between slides in Overfitting/Underfitting (possibly elsewhere as well)

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#143]
As @GaelVaroquaux said in the chat (translation and rephrasing mine):
> Ideally we would alternate concept presentation and notebooks to explore this concepts 
> In "overfitting / underfitting" this is particularly true and we could also do notebooks about learning curves after the slides

I kind of agree that in a ideal world, we would produce the same plots (or at least similar plots) we showed in the slides with the full code as a way to explain the same thing but with code, so that people have a bit more chance to understand.

**Comment by glemaitre** [comment]
I cut the notebook of cross-validation in:

- train/test errors
- validation curve / underfit-overfit
- learning curve

I think that the 2 first notebooks could be moved between the slides.

**Comment by lesteve** [comment]
One of the thing I am still wondering about is whether we should aim to reproduce the same plots as the one in the slides or not.

**Comment by GaelVaroquaux** [comment]
Not exact reproduction, but conveying some of the ideas seems nice.
