### ISSUE TITLE
Issue on page /python_scripts/parameter_tuning_automated.html

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#147]
https://inria.github.io/scikit-learn-mooc/python_scripts/parameter_tuning_automated.html

- [ ] there is an opportunity to split this in two separating GridSearchCV and RandomizedSearchCV
- [ ] there are some quizzes inside the notebook that should probably be removed, moved to real quizzes or maybe left as a question without multiple choices, e.g. "can you find parameters that are important for generalization performance"?

**Comment by glemaitre** [comment]
Yes I did not exactly what to do with this final quizz :)
