### ISSUE TITLE
Better word than performance for statistical performance?

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#149]
Are we fine with using performance for statistical performance, i.e. better score on the test set? If not what would be a better word, "generalization performance", "test score", something else?

For people with some experience in computer science, performance kind of relates to how fast something runs. I found myself mentioning this caveat (I used "statistical performance") a number of times when giving the course in front of IN2P3 computer scientists a few months ago.

Maybe it is just me who talks too much with HPC people in a Jean Zay context in the last few months ...

**Comment by GaelVaroquaux** [comment]
> Are we fine with using performance for statistical performance,

Bien vu!

Just "performance" in itself is ambiguous. It may be understood as
computational performance.

> If not what would be a better word, "generalization performance",

I think that "generalization performance" is a good phrasing.

I suggest to define generalization performance the first time that we use
it, with a small paragraph (as formating, we can use something as simple
as starting the paragraph with "Generalization performance" in bold).

**Comment by glemaitre** [comment]
I sometime wrote `performance in terms of {metric name}` as well.
