### ISSUE TITLE
Figs for the linear-regression chapter

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#15]
As discussed with @TwsThomas today:

# Figures about OLS, logistic and SVM

(I cannot attach the code that I have for that, I'll have to do a PR)

# A figure about bias-variance in the ridge

Adapted from http://scipy-lectures.org/packages/scikit-learn/index.html#bias-variance-trade-off-illustration-on-a-simple-regression-problem

**Comment by lesteve** [comment]
I think this has been done.
