### ISSUE TITLE
Overlap between introductory example for hyperparameters tuning and manual tuning

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#161]
![image](https://user-images.githubusercontent.com/1680079/105020344-765e4700-5a47-11eb-8ffa-10291f5fa90b.png)

- [ ] "Introductory example ..." should be moved to manual tuning maybe ?
- [ ] tt seems like there is some overlap (after it was moved) but maybe not?

**Comment by GaelVaroquaux** [comment]
Sounds right to me. Thanks for spotting this!

**Comment by lesteve** [comment]
Removed introductory example in https://github.com/INRIA/scikit-learn-mooc/commit/cd6343911d0a115997b0ef2caa221407cc3f022d.

**Comment by lfarhi** [comment]
OK, supprimé dans FUN
