### ISSUE TITLE
Single and not great quiz for Hyper-parameters tuning

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#162]
![image](https://user-images.githubusercontent.com/1680079/105020623-d359fd00-5a47-11eb-8041-c62dc50f6c21.png)

Probably should be enhanced, split into multiple quizzes (one per sequence in an ideal world) and moved to the appropriate sequence.

**Comment by lfarhi** [comment]
OK, dans FUN
