### ISSUE TITLE
Enhance/split/move Model Performance quizzes

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#163]
![image](https://user-images.githubusercontent.com/1680079/105020952-45324680-5a48-11eb-9362-44b601834ff6.png)

Ideally one quiz per sequence

**Comment by lesteve** [comment]
Hmmm not sure why there is the FUN:changes done label on this one since we have not done it (one quiz per sequence) in our repo.

I am going to remove the label. @lfarhi don't hesitate to comment if I am missing something.

**Comment by glemaitre** [comment]
I had a look in FUN-campus and the TOC is similar to our jupyter-book so we still need to split and reorganize the quizzes.

**Comment by lfarhi** [comment]
This time, it's done in FUN !
in the new instance : https://www.fun-mooc.fr/courses/course-v1:inria+41026+session01/courseware/cb3cfcaf0cae4cf7801c4e8d5dab9087/6b6731448ac048f18b446bf6b9bc1623/
