### ISSUE TITLE
Dataset transition between adult_census (Predictive Modeling Pipeline) and boston_housing (Select the Best Model) and then back to adult_census (HyperParameter Tuning)

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#165]
Now that the hyper-parameter tuning has been moved out of the modelling predictive pipeline part, we do:
- adult_census for Modeling Predictive Pipeline
- boston_housing for Selecting the Best Model
- back to adult_census for Hyperparameter tuning

do we care?

Can we use adult_census for Selecting the Best Model?

**Comment by GaelVaroquaux** [comment]
> Can we use adult_census for Selecting the Best Model?

We should try, it would probably help streamlining the teaching.

**Comment by glemaitre** [comment]
I think that this is actually useful to have a regression dataset for the module on the evaluation.
It allows putting in perspective the variation of the target in a natural unit. It might not be so easy to have similar intuitions with classification.

**Comment by lesteve** [comment]
Let's close this as not important enough.
