### ISSUE TITLE
Simplification / improvement / removal of plots for ordinal and one-hot encoded encoding

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#167]
### OrdinalEncoder
https://inria.github.io/scikit-learn-mooc/python_scripts/03_categorical_pipeline.html#encoding-ordinal-categories

![image](https://user-images.githubusercontent.com/1680079/105394962-82e8c800-5c1e-11eb-9453-f9b0b15b256f.png)
this was not clear that this plot was really useful

### OneHotEncoder
https://inria.github.io/scikit-learn-mooc/python_scripts/03_categorical_pipeline.html#encoding-nominal-categories-without-assuming-any-order

![image](https://user-images.githubusercontent.com/1680079/105395040-9a27b580-5c1e-11eb-93ea-601c615bddf3.png)
maybe showing the dataframe is enough. Maybe chose some column with low cardinality so that the Dataframe is not too wide.

**Comment by glemaitre** [comment]
We need to place the "Gender" and "Marital Status" first.
