### ISSUE TITLE
Wrong intro for numerical + categorical variables together

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#168]
https://inria.github.io/scikit-learn-mooc/python_scripts/03_categorical_pipeline_column_transformer.html#using-numerical-and-categorical-variables-together

Intro:
> In this notebook, we will present typical ways to deal with categorical variables, namely ordinal encoding and one-hot encoding.

This is not the case, here we are going to use categorical and numerical variables together.

It seems like the intro/summary parts of the categorical variables are wrong. We would need to check them for this whole section ...

I fixed https://github.com/INRIA/scikit-learn-mooc/commit/a09510bc2e26fb34dabfc1567a7bc3cc2272bc10 yesterday but there may be other problems in this sequence.

**Comment by Phaide** [comment]
Hello,

I believe it was fixed by #157 (https://github.com/INRIA/scikit-learn-mooc/pull/157/files#diff-c22f795fddb1de5f08ee75399c8b188cb3874477c8513459d31a890a7090ed07)

**Comment by lesteve** [comment]
Thanks I am going to trust you on this one and close this issue. If related problems surface again we can fix them in a separate issue.
