### ISSUE TITLE
Missing cell delimiter (likely or something else)

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#170]
https://inria.github.io/scikit-learn-mooc/python_scripts/parameter_tuning_manual.html#set-and-get-hyperparameters-in-scikit-learn

![image](https://user-images.githubusercontent.com/1680079/105490072-829b0c00-5cb4-11eb-90b0-f2c917333c78.png)

**Comment by lesteve** [comment]
While I am at it we should score before doing `get_params` to show that there is a difference

**Comment by glemaitre** [comment]
I did the small change so it remains only the `get_params`
