### ISSUE TITLE
Wrong wrap-up in notebook about categorical

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#171]
In the categorical notebook, we mention the combination of numerical and categorical.

**Comment by glemaitre** [comment]
It was not true because we only tackle the categorical at this stage

**Comment by lesteve** [comment]
I think I fixed this one in https://github.com/INRIA/scikit-learn-mooc/commit/a09510bc2e26fb34dabfc1567a7bc3cc2272bc10
