### ISSUE TITLE
Datasets in /figures

### ISSUE THREAD

**Issue by brospars** [INRIA/scikit-learn-mooc#176]
Hello,

I have a small issue regarding 2 datasets in `/figures` instead of `/datasets`, since I don't clone the entire repository it's missing on the learner's environment.

- `/figures/randomized_search_results.csv`
- `/figures/randomized_search_results_logistic_regression.csv`

Should I open a PR to move them ?

**Comment by lesteve** [comment]
Hmmm I think sometimes the `figures` folder is used inside the notebooks, typically when we want to include a plot to give some intuitions but we don't want to show the code behind it.

For example: https://github.com/INRIA/scikit-learn-mooc/blob/845ac1bdc55db3a613aa61711a9c716c5eb80ebc/python_scripts/01_tabular_data_exploration.py#L232

Would it be possible to download figures as well (16 MB right now this may grow a bit in the future)?

**Comment by brospars** [comment]
Ok I'll add it.

**Comment by lesteve** [comment]
Great thanks!
