### ISSUE TITLE
ConvergenceWarning and introduction scaling numerical features 

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#179]
https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_scaling.html#model-fitting-without-preprocessing

It is a bit weird to set explicitly `max_iter` to trigger a `ConvergenceWarning`. IIRC the output of the discussion with @ogrisel and @glemaitre was that we should:
- forget about the `ConvergenceWarning`, i.e. not set artificially a low `max_iter` to trigger it
- emphasize that scaling the numerical feature converges in less iterations and less time

For more context, previously the `ConvergenceWarning` was triggered without setting `max_iter` but by removing `education-num` it is not triggered any more with the default `max_iter`

**Comment by glemaitre** [comment]
As discussed, I will remove this section. I will add a small note at instead.
In addition, I will add a subsequent note somewhere where we force `max_iter` because of this issue.
