### ISSUE TITLE
Obscure statement

### ISSUE THREAD

**Issue by Phaide** [INRIA/scikit-learn-mooc#181]
In https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_regularization.html 

> It means that our model is far worth than predicting the mean of `y_train`.

There is a problem of phrasing, and I don't understand what this sentence wants to say.
Could you please clarify ?

**Comment by lesteve** [comment]
Typical Frenchism probably `worth` -> `worse`. What do you mean they are not pronounced the same, are you serious I can not tell the difference :wink:?

**Comment by lesteve** [comment]
Sometimes it helps a lot to read the sentence aloud with your best typical French accent :wink:

**Comment by Phaide** [comment]
Haha you're probably right !
I'll submit a PR asap :)
