### ISSUE TITLE
Unnecessary repetition

### ISSUE THREAD

**Issue by Phaide** [INRIA/scikit-learn-mooc#182]
In https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_regularization.html

> Instead of calling the transformer to transform the data and then calling the regressor, scikit-learn provides a Pipeline, which ‘chains’ the transformer and regressor together. The pipeline allows you to use a sequence of transformer(s) followed by a regressor or a classifier, in one call. (i.e. fitting the pipeline will fit both the transformer(s) and the regressor. Then predicting from the pipeline will first transform the data through the transformer(s) then predict with the regressor from the transformed data)
> 
> This pipeline exposes the same API as the regressor and classifier and will manage the calls to fit and transform for you, avoiding any problems with data leakage (when knowledge of the test data was inadvertently included in training a model, as when fitting a transformer on the test data).
> 
> We already used Pipeline to create the polynomial features before training the model.

I believe this is a subject already covered earlier.

Therefore, we could truncate this section to a sentence or two, like:

> *Instead of calling the transformer on the data and then calling the regressor, we will use a Pipeline to automate this process, as we saw in an earlier notebook.*

**Comment by lesteve** [comment]
My personal take is that it is completely OK to repeat some small things between modules. Sometimes this may even be beneficial to remind people of important things.

More generally the material may be used for different settings than only the MOOC e.g. remote teaching.

**Comment by glemaitre** [comment]
I made a pass when reworking the linear module. I simplified the discussion by not showing code and just recalling the need of scaling with some discussion.
