### ISSUE TITLE
Mismatch between exercise and solution notebooks

### ISSUE THREAD

**Issue by Phaide** [INRIA/scikit-learn-mooc#183]
In https://inria.github.io/scikit-learn-mooc/python_scripts/trees_ex_01.html

> ax.set_xlabel(feature_names[0])
> ax.set_ylabel(feature_names[1])

Those two lines of Python from the function `plot_decision_function` do not appear in the solution notebook, so I guess they are useless and we could remove them, right ?

**Comment by lesteve** [comment]
I am wondering if there could be some way to put together some quick test for discrepancies. Basically the solution file cells should contain all the exercise file cells (maybe without a "Write your code here" lines). Maybe also a script that generate exercise from solution. We could reuse a similar idea as what we do for quizzes and solutions. 

As always maybe this is over-engineering at this point and we should focus on the content instead.
