### ISSUE TITLE
Only studying max_depth hyperparameter when saying "some key hyperparameters" in notebook intro

### ISSUE THREAD

**Issue by Phaide** [INRIA/scikit-learn-mooc#185]
In https://inria.github.io/scikit-learn-mooc/python_scripts/trees_hyperparameters.html

It is said in the beginning: 
> In this notebook, we will illustrate the importance of **some key hyperparameters** on the decision tree

However, by the end of the notebook, only one was seen, `max_depth`.
It concludes with
> The other parameters are used to fine tune the decision tree and have less impact than `max_depth`.

We should either dedicate this notebook to this parameter, or add information on some others.

**Comment by lesteve** [comment]
Probably the quickest fix is to fix the intro.
