### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by Phaide** [INRIA/scikit-learn-mooc#187]
In https://inria.github.io/scikit-learn-mooc/python_scripts/cross_validation_train_test.html

> [...] cross-validation is a bit than the natural scale [...]

A word is missing after *bit*, I don't know which one though.

**Comment by lesteve** [comment]
I guess "smaller" maybe @glemaitre can confirm.

Just so you know you can have hypothesis links like this: https://hyp.is/kL_S_ktkEeus3p-zfmZjNw/inria.github.io/scikit-learn-mooc/python_scripts/cross_validation_train_test.html

There is an icon to get this link at the bottom right:
![image](https://user-images.githubusercontent.com/1680079/106926814-c7419100-6711-11eb-89fa-16de904fa701.png)

**Comment by glemaitre** [comment]
Yes "smaller" it is. The mean generalization error is 45 k$ and the std of the natural scale is 115 k$.
