### ISSUE TITLE
Dollars in notebooks

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#189]
In jupyter-book, dollar signs need to be escaped with one slash, and render well here
https://inria.github.io/scikit-learn-mooc/python_scripts/cross_validation_train_test.html
But in a notebook, we need a double slash to protect the dollar (see the above notebook in jupyter).

I don't know how to solve this :(.

**Comment by GaelVaroquaux** [comment]
I tried to start a discussion here: https://github.com/executablebooks/jupyter-book/issues/750

**Comment by ogrisel** [comment]
In jupyter-book we have:

```
<script type="text/javascript" async="" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

**Comment by lesteve** [comment]
I did not think of it right away but a pragmatic approach might be to replace `\$` -> `\\$` when we convert `.py` to `.ipynb`.

We already have a script to generate HTML admonition in https://github.com/INRIA/scikit-learn-mooc/blob/master/build_tools/convert-python-script-to-notebook.py in the `.py` -> `.ipynb` conversion.

Full disclosure: in Binder right now the notebooks use the `.py` files (it was easier to set up this way), so no HTML admonition or escaped dollars in Binder. I guess that's fine for now, I'll create an issue about this.
