### ISSUE TITLE
Pair .py files to notebooks or rendered_notebooks folder?

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#19]
The `python_scripts/bla.py` files are still paired to `notebooks/bla.ipynb`. That means that using Jupytext extension from JupyterLab or Jupyter notebook server, opening the `.py` file as notebook and saving will write the companion notebook to `notebooks/bla.ipynb`.

Should `python_scripts/bla.py` be paired with `rendered_notebooks/bla.ipynb` instead?

This feels more consistent and would allow to regenerate the rendered notebook from Jupyter rather than through the `Makefile`.

For people more likely to use the "Open .py file as notebook" @GaelVaroquaux @ogrisel @glemaitre let me know what you think!

**Comment by GaelVaroquaux** [comment]
> Should python_scripts/bla.py be paired with rendered_notebooks/bla.ipynb instead?

I thought that we were not using the pairing anymore.

But maybe you are right. In which case, they should be paired with
rendered_notebooks

**Comment by glemaitre** [comment]
To be honest, I only used the `.py` file (99% in VS Code - 1% in jupyter notebook for checking the rendering). So I think that we should not have the `notebooks/*` anymore.

Regarding the `rendered_notebooks/*`, if the idea behind is
* to have a rendered version which could be handy under some circumstances;
* to have a format that a Jupyter user knows about without the need to install `jupytext`;
then I think the pairing could be useful. Basically I see this part useful for on the side of the user (opposed to the content developer)

@lesteve I don't recall: does the pairing if both direction or only from py -> ipynb

**Comment by lesteve** [comment]
> @lesteve I don't recall: does the pairing if both direction or only from py -> ipynb

I think it is supposed to work both ways. With the "Open .py as notebook" you never need to open the notebook though.

> I thought that we were not using the pairing anymore.

We are (it's still in the metadata) hence the save behaviour I mentioned. I don't know wether we have to though and maybe we can get rid of it ...

**Comment by lesteve** [comment]
So after a small test it seems like we don't need the pairing to use the "Open .py as notebook" approach.

I propose we get rid of the pairing it for simplicity reason. That means that people using this approach have to use `make` to rerender the notebook. At least that guarantees that the notebook is always run from scratch.

Any objections to getting rid of the pairing?

**Comment by glemaitre** [comment]
None on my side

**Comment by lesteve** [comment]
Fixed by f09aa6b1c5a0068a64dbaed2b5cd1e752848932d

**Comment by brospars** [comment]
Sorry I'm a little late but I was using non-rendered noteboks to init learner's environment. I could find a workaround and clear the outputs but the files are much bigger to download...

**Comment by lesteve** [comment]
I think we should get rid of rendered notebooks in the not too far future. JupyterBook seems like a fine replacement to browse the rendered notebooks. Also rendered notebooks and git is a bit painful (in particular with plotly HTML plots).

You can manually generate empty notebooks with jupytext:
```
jupytext --to notebook <input-python-file> --output <output-notebook-file>
```

**Comment by brospars** [comment]
Ok I'll do that thanks.
