### ISSUE TITLE
Issue regarding intermediate md file serving as transition within a module

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#197]
FUN does not allow to use md file within a module while we are using such file in jupyter-book.
The index can be listed with: 

```
(for f in $(git ls-files '*index*.md'); do wc -l $f;
done) | sort -nr
```

and the files that are problematic are:

```
14 jupyter-book/evaluation/cross_validation_choices_index.md
12 jupyter-book/tuning/parameter_tuning_manual_index.md
11 jupyter-book/overfit/cross_validation_index.md
8 jupyter-book/evaluation/cross_validation_baseline_index.md
```

**Comment by glemaitre** [comment]
We could attend to replace these files by some jupyter notebook or otherwise, check if we could include the transition within the next notebook.

**Comment by lesteve** [comment]
I think the easiest thing to do is to include the content in the first notebook of a sequence.

It is a bit of work but in an ideal world I think it would make sense to add a separate .md file at a beginning of each sequence with a small overview of what we are going to cover in the sequence.

**Comment by lesteve** [comment]
Update of the suspicious files:
```
13 jupyter-book/evaluation/cross_validation_choices_index.md
12 jupyter-book/tuning/parameter_tuning_manual_index.md
8 jupyter-book/evaluation/cross_validation_baseline_index.md
```
