### ISSUE TITLE
Fix remarkjs-pdf timeout

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#22]
I was annoyed to have the CI red because of the remarkjs-pdf timeout so I commented it out in https://github.com/INRIA/scikit-learn-mooc/commit/b92c7cf7b1a40fbd16518bd5f30c70b379207532.

If you have time to look at it @brospars maybe by patching remarkjs-pdf to have a bigger timeout (as you did in your PR to remarkjs-pdf) or using decktape to generate the PDF (as mentioned in the remark.js doc [here](https://github.com/gnab/remark#printing)), that would be much appreciated.

_Originally posted by @lesteve in https://github.com/INRIA/scikit-learn-mooc/issues/14#issuecomment-646691960_

**Comment by brospars** [comment]
The issue is deeper than that. Even without timeout overfit.html won't load on chrome (tested locally on chromium). It's due to htmlark inlining all images.

**Comment by brospars** [comment]
If we move all figures to `/figures` and remove `htmlark` it could work.

**Comment by lesteve** [comment]
I am afraid I am not following (probably because this web stuff is not my area of expertise ...), maybe you open a PR and get feed-back from @GaelVaroquaux who did this part originally?

**Comment by lesteve** [comment]
Probably this can be closed since #23 was merged.
