### ISSUE TITLE
Quiz solution sync

### ISSUE THREAD

**Issue by ogrisel** [INRIA/scikit-learn-mooc#223]
This is an isssue to track changes that need manual synchronization in the mooc platforms:

https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/commit/c960baf1f8ff7d8d67e404a62a25b41e425ce8d8

**Comment by ogrisel** [comment]
https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/commit/c960baf1f8ff7d8d67e404a62a25b41e425ce8d8

**Comment by glemaitre** [comment]
I also tagged the PRs: https://github.com/INRIA/scikit-learn-mooc/pulls?q=is%3Apr+is%3Aclosed+label%3A%22FUN%3Arequires+changes%22

**Comment by glemaitre** [comment]
I am closing this issue since it has been addressed.
