### ISSUE TITLE
Add figure of the effect of StandardScaler in the M2 wrap quiz correction

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#225]
@ogrisel proposes to add an additional figure: https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/8#note_477599 

It is probably not dramatic for the next course but we should address it.
I am putting this issue as a reminder.

**Comment by lesteve** [comment]
Is this still relevant in the context of the MOOC 1.0 release or should we move it to the MOOC 2.0 milestone?

**Comment by glemaitre** [comment]
I assume it can be postponed to v2

**Comment by ogrisel** [comment]
Having tried with @ArturoAmorQ to experiment with adding a new figure, I don't think it's necessary / useful anymore. What @ArturoAmorQ changed in #662 should be enough to fix the original problem described in #646.
