### ISSUE TITLE
Inconsistent wrap up quiz location

### ISSUE THREAD

**Issue by brospars** [INRIA/scikit-learn-mooc#226]
Last month @lesteve [moved](https://github.com/INRIA/scikit-learn-mooc/commit/e1508c80b1dfe1948cbc14d25c01fdf1b99443ab) `evaluation/predictive_modeling_pipeline_questions.md` to `jupyter-book/predictive_modeling_pipeline/wrap_up_quiz.md ` but other wrap up quizzes remain in `evaluation/`.

It's easier for me if they are all in `evaluation/`since I can list them all and create corresponding empty notebooks. 

Would you mind changing it back ?

Thank you !

**Comment by glemaitre** [comment]
nop I will do that now.

**Comment by glemaitre** [comment]
I think that those quizz in `evaluation` are out of sync. The quizzes are already in the right directories:

```
./overfit/overfit_wrap_up_quiz.md
./trees/trees_wrap_up_quiz.md
./ensemble/ensemble_wrap_up_quiz.md
./predictive_modeling_pipeline/wrap_up_quiz.md
./linear_models/linear_models_wrap_up_quiz.md
```
@ogrisel  is going to add one in `parameter_tuning` folder.

**Comment by glemaitre** [comment]
I will remove the evaluation folder then.

**Comment by glemaitre** [comment]
Solved in the `master` branch
