### ISSUE TITLE
Wrong number of features displayed in tabular exploration notebook

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#227]
The following is wrong:

https://github.com/INRIA/scikit-learn-mooc/blob/9ed7fe868d8c23efd003f570f72264fb5c643539/python_scripts/01_tabular_data_exploration.py#L120-L122

`X` contains the target. Thus, the number of feature is `X.shape[1] - 1`.

**Comment by lesteve** [comment]
Hmmm not sure about this, since we redefine the variable later to contain only the features we care about:

https://github.com/INRIA/scikit-learn-mooc/blob/9ed7fe868d8c23efd003f570f72264fb5c643539/python_scripts/01_tabular_data_exploration.py#L100-L109

Maybe I am missing something?

**Comment by glemaitre** [comment]
Yes but `target_column` is indeed in `all_columns` and we filter using `all_columns` :)

**Comment by glemaitre** [comment]
It is subtle, just found it while teaching :)

**Comment by lesteve** [comment]
Indeed :cry:

**Comment by glemaitre** [comment]
Solved in master
