### ISSUE TITLE
DummyClassifier not visible in ROC curve

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#240]
https://inria.github.io/scikit-learn-mooc/python_scripts/metrics_classification.html
The text states that there should be a green line showing a dummy classifier on the ROC curve, but I don't see it

**Comment by glemaitre** [comment]
My bad, I updated with the new plotting function but forgot to add the chance level.
In addition, we should capture the display to avoid printing the object representation.
