### ISSUE TITLE
Credit original authors by using some of their figure

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#249]
When creating the diagram, we reused some external figure. I checked that these figures could be used. Some licences are CC-by and we will need to acknowledge the usage. I think that we can even do that for the one that are CC-0 as well.

Here are the links to the figures used:

* https://www.onlinewebfonts.com/icon/512285 - Licence CC-BY 3.0
* https://www.svgrepo.com/svg/57066/settings-gears - Licence CC0
* https://www.iconfinder.com/icons/211652/close_icon - Licence MIT

What would be the proper way to acknowledge these usages. ping @lfarhi @GaelVaroquaux @ogrisel @lesteve

**Comment by GaelVaroquaux** [comment]
> What would be the proper way to acknowledge these usages.

Somewhere in the MOOC (appendices, for instance), the link to the
original work, as well as the name of the author and the original licence
should appear.

**Comment by lfarhi** [comment]
ok, I note that we have to find a place for the credits, probably in the Welcome chapter
