### ISSUE TITLE
Inconsistency of linear regression plots in two close linear regression notebooks

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#270]
### without scikit-learn
https://inria.github.io/scikit-learn-mooc/python_scripts/linear_regression_without_sklearn.html
![image](https://user-images.githubusercontent.com/1680079/113406869-8336d980-93ac-11eb-8a8f-8a1411903662.png)

### with scikit-learn
https://inria.github.io/scikit-learn-mooc/python_scripts/linear_regression_in_sklearn.html
![image](https://user-images.githubusercontent.com/1680079/113406825-74502700-93ac-11eb-8d98-99d55c182961.png)

My personal opinion: I am fine with the blue data points (without alpha transparency) and orange line.

**Comment by glemaitre** [comment]
> My personal opinion: I am fine with the blue data points (without alpha transparency) and orange line.

I might tend for the second solution. We use it as well in other plots and it allows to avoid specifying the colors for the line.
