### ISSUE TITLE
Remove hypothesis side-panel with content_only parameter

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#272]
https://inria.github.io/scikit-learn-mooc/appendix/glossary.html?content_only

![image](https://user-images.githubusercontent.com/1680079/113803785-81c73180-975d-11eb-82dd-5d38c5f9e5ea.png)

On the right-hand side the hypothesis panel is visible. This is also visible in the FUN platform which probably we don't want. This affects also exercise solutions.

Not sure how easy this is to remove with javascript ...

cc @brospars

**Comment by brospars** [comment]
Are you using Hypothesis ? If not we can disable it entirely.

**Comment by lesteve** [comment]
If that's too complicated to remove it from the FUN side we can remove it on the `.github.io` website (this is a setting in JupyterBook somewhere).

It'd be nice to keep it in an ideal world (e.g. for quick feed-back or notes on the content) but that's not the world we live in ...
