### ISSUE TITLE
Remove fnlwgt from CSV

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#278]
This is the simplest. It makes slightly inconsistent with the OpenML dataset but easier not to have to explain why we drop this column (we don't really know actually how it was constructed)

**Comment by GaelVaroquaux** [comment]
+1 on droping. It makes things easier.

> (we don't really know actually how it was constructed)

It's a propensity score. But let's not go in these details.

**Comment by lesteve** [comment]
> But let's not go in these details.

This should be the motto for this MOOC phase I think.

**Comment by GaelVaroquaux** [comment]
> This should be the motto for this MOOC phase I think.

+1
