### ISSUE TITLE
Consider getting rid of the decision tree plot in the data exploration notebook

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#283]
this is a bit hard to explain and this feels out of place compared to the rest of the notebok which is about data exploration.

I think we said that this would make more sense to show a visual hand-made rule with matplotlib vline hline and have a plot that shows:
- left -> low income
- bottom right -> low income
- top right -> ??? (i.e. we don't know)

also mention in one sentence that a decision tree would give simlar rules and help in the top-right cadrant (I think we already say this a bit)

**Comment by glemaitre** [comment]
take

**Comment by lesteve** [comment]
I am the take bot now 😉
