### ISSUE TITLE
wrap quiz 3

### ISSUE THREAD

**Issue by ogrisel** [INRIA/scikit-learn-mooc#295]
Question 1: move hint (`scoring="balanced_accuracy"`) into the instructions rather than a hint

**Comment by lesteve** [comment]
The rest of the wrap-up quiz with plotly parallel coordinate plots needs to be looked at as well (probably too many possible answers that could be splitted or maybe reduced)

**Comment by glemaitre** [comment]
@lesteve I open https://github.com/INRIA/scikit-learn-mooc/issues/299 regarding the wrap up quiz.
