### ISSUE TITLE
Simplify two pipeline diagrams to have only one transformer

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#327]
Question I had twice in the same session: hmmm why are there two transformers in the diagram but only one in the code. 
https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_scaling.html
![image](https://user-images.githubusercontent.com/1680079/117233373-49317b00-ae23-11eb-8a9d-f8a84ec4f62f.png)
and
![image](https://user-images.githubusercontent.com/1680079/117233588-b2b18980-ae23-11eb-9876-dfe2cacbe28d.png)

I think we should have only one transformer in the diagram to have the simple case and mention in the text that in the more general case you can have many transformers and that we will see that in one of the next notebook.

A more pragmatic reason to simplify the diagram is that it is too wide and that text is not readable at all.

@ogrisel agreed but said that we should keep the more complicated diagram in the .drawio project in case we want to reuse it.

**Comment by lesteve** [comment]
Also an opportunity to do `predictor.predict` -> `model.predict` in the last box, since "predictor" is a bit jargony. I think @ogrisel was not 100% OK with the idea because `pipeline` is a model as well so maybe this one is for later ...

**Comment by glemaitre** [comment]
I changed the graph and stored the complex pipeline in 2 new sheets in draw.io
I did not change the name of the predictor for now.

**Comment by glemaitre** [comment]
I am going to check if we need to adapt some of the discussion but I think we were quite fine.
