### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by ThomasBourgeois** [INRIA/scikit-learn-mooc#330]
in "ensemble_bagging.ipynb" : 
Once our trees are fitted and we are able to get predictions for each of them. In regression, the most straightforward way to combine those predictions is just to average them: for a given test data point, we feed the input feature values to each of the n trained models in the ensemble and as a **resutl** compute n predicted values for the target **varible**. The final prediction of the ensemble for the test data point is the average of those n values.

**Comment by glemaitre** [comment]
Thanks

**Comment by glemaitre** [comment]
fixed in 0845e5d914fba91cb3e39e0541c49acb026ae587

**Comment by ThomasBourgeois** [comment]
wow, too fast, I was closing it alongside.. I should have mentionned it !

**Comment by glemaitre** [comment]
Ups sorry :)

**Comment by lesteve** [comment]
Thanks a lot @ThomasBourgeois if you notice other typos let us know! In case you want to propose PRs maybe a few things that could be useful:
- modifying the `.py` files in `python_scripts` is the right thing to do, this is the source of truth not the `.ipynb`
- this may help to look at https://github.com/INRIA/scikit-learn-mooc/blob/master/CONTRIBUTING.md (but sorry the things are not as newcomer-friendly as it could be)
