### ISSUE TITLE
High-level overview of the pedagogical structure

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#332]
Now that the course content is a bit more mature, should we create a single document kind of summarising the key elements of each notebook so that we can have an idea of the high-level pedagogical structure? This would be a single document so maybe this is a rehash of `plan.md` that never really worked ...

This helps having a high-level overview of the full content. Very often when changing something locally:
- you don't realise that you need to change it in other places
- that the pedagogical sequence is a bit weird once you change it
- or that originally we did that because we thought we would not introduce a notion until a later module.

Should this be automatically generated (probably not)?

Should we do it now that the course content is fresh in our minds?

Maybe this is YAGNI I don't know

**Comment by GaelVaroquaux** [comment]
I think that this would be useful. Maybe ask the learning lab team what they think?

**Comment by lfarhi** [comment]
We have a table of content in the Mooc : https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session01/496272d6f8444957a7014122a4646116/ and it is very usefull even if we could improve it with some collapse elements. Is it somethink similar that you wish @lesteve ?

**Comment by lesteve** [comment]
For me this is more a single document that includes the table of content but also some text explaining the idea behind each notebook so that we can use it to see the full story of the MOOC (more for us as content writers than anything else).

I'll open a separate issue about having the equivalent of the FUN table of contents, I agree this would be useful to quickly make sure that the contents haven't drifted too much away between FUN and the JupyterBook.

**Comment by ArturoAmorQ** [comment]
> should we create a single document kind of summarising the key elements of each notebook so that we can have an idea of the high-level pedagogical structure? 

Maybe a table of contents similar to the one that I use in #398 could come useful for this purpose. Of course my notation can be improved using navigation tools, but it does help keeping track of the pedagogical structure.

> Should we do it now that the course content is fresh in our minds?

I am expanding it while following the MOOC.

**Comment by lesteve** [comment]
Let's close this, I don't think this is realistic to have something like this unfortunately ...

Also there is the table of contents now: https://inria.github.io/scikit-learn-mooc/toc.html
