### ISSUE TITLE
Have the equivalent of the FUN table of contents inside JupyterBook

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#335]
From https://github.com/INRIA/scikit-learn-mooc/issues/332#issuecomment-833413354.

Have the equivalent of the FUN table of contents https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session01/496272d6f8444957a7014122a4646116/

![image](https://user-images.githubusercontent.com/1680079/117300207-a0623a80-ae79-11eb-8099-1e2593565a57.png)

There was the `{tableofcontents}` directive which included in `index.md` would show a good start but only one level deep and we need two levels e.g.: Module 2 -> Fitting a scikit-learn model -> First look at our dataset

**Comment by lesteve** [comment]
The `tableofcontents` directive code is here https://github.com/executablebooks/jupyter-book/blob/8be06d8b8920d4967737d7ffec91af691d7100b1/jupyter_book/directive/toc.py#L19. I don't understand jupyter-book or sphinx well enough to see whether it would be doable to:
- extend it to 2 level deep. I even created a jupyter-book issue about this: https://github.com/executablebooks/jupyter-book/blob/8be06d8b8920d4967737d7ffec91af691d7100b1/jupyter_book/directive/toc.py#L19
- make it so that `{tableofcontents}` can be used anywhere not only in `index.md`

**Comment by lesteve** [comment]
Actually a quick-hacky solution would be to type something in the browser console to expand all the sections (as if you clicked by hand) ... maybe @brospars or @lfarhi could help, if you manage to get something working let me know I would find this very useful!

I think something based on the  finding all the elements based on the "fa-chevron-up" class and `.click()` should work!

**Comment by lesteve** [comment]
Another possibility would be to look at https://github.com/executablebooks/sphinx-external-toc which is used in JupyterBook and see whether we can get a HTML table of contents out of our `_toc.yml` file ...

**Comment by brospars** [comment]
I'll take a look for next session.
