### ISSUE TITLE
Hints in quizzes were converted into FUN quiz hints although they should probably be visible without clicking

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#345]
Sometimes hints in our `.md` quiz files were not meant to be converted into FUN quiz hints where you need:
1. be knowledgeable enough to know "well this question does not have enough information to be answered"
2. remember that clicking on the Hint box is something you can do

I am not too sure whether most people would think of doing 2. but when we were looking at feed-back from the beta quizzes grades we were confused originally that the question was so hard to ask.

We should probably wait for user feed-back but maybe looking at a few quizzes before the users complain (or have some bad grades on some quizzes) could be a good idea.

Maybe we can agree on a convention in our `.md` files to say this is is a hint that should always be visible (i.e. not a FUN hint where you need to click). Suggestions more than welcome for a better word ...

An example I found:
![image](https://user-images.githubusercontent.com/1680079/117392546-9597bc00-aef2-11eb-9030-041b2864c770.png)
https://inria.github.io/scikit-learn-mooc/predictive_modeling_pipeline/02_numerical_pipeline_quiz_m1_02.html

In this case I think we want the hint to be visible (i.e. not a FUN quiz hint). We want the person to look at the previous question plots and try to say in words what they mean, rather than think hard and only if they are stuck click on the Hint button and actually gets the answer.

**Comment by lesteve** [comment]
A `git grep` to look at the quizzes where we have hints:
```
❯ git grep Hint jupyter-book/*/*quiz*.md
jupyter-book/ensemble/ensemble_quiz_m6_02.md:Hint: it is possible to access the documentation for those classes by
jupyter-book/evaluation/evaluation_wrap_up_quiz.md:Hint: pass `scoring="neg_mean_absolute_error"` to the `cross_validat
jupyter-book/evaluation/evaluation_wrap_up_quiz.md:Hint: it is possible to replace the negative acceleration values by 
jupyter-book/evaluation/evaluation_wrap_up_quiz.md:Hint: look at the values of the `train_score` and the `test_score` c
jupyter-book/evaluation/evaluation_wrap_up_quiz.md:Hint: You can check the unique day in the `DatetimeIndex` (the index
jupyter-book/evaluation/evaluation_wrap_up_quiz.md:Hint: You can access to the date and time of a `DatetimeIndex` using
jupyter-book/linear_models/linear_models_wrap_up_quiz.md:Hint: you can use `df.info()` to get information regarding eac
jupyter-book/linear_models/linear_models_wrap_up_quiz.md:Hint: you can use `df.info()` to get information regarding eac
jupyter-book/overfit/overfit_wrap_up_quiz.md:Hint: `target.unique()`, and `target.value_counts()` are methods
jupyter-book/overfit/overfit_wrap_up_quiz.md:Hint: You can check the documentation of `sklearn.model_selection.cross_va
jupyter-book/overfit/overfit_wrap_up_quiz.md:Hint: You can use `model.get_params()` to get the parameters of a scikit-l
jupyter-book/overfit/overfit_wrap_up_quiz.md:Hint: compute the average test score and the average train score and compa
jupyter-book/predictive_modeling_pipeline/02_numerical_pipeline_quiz_m1_02.md:Hint: look at the plots and the answers o
jupyter-book/predictive_modeling_pipeline/wrap_up_quiz.md:Hint: you can use the method
jupyter-book/tuning/parameter_tuning_wrap_up_quiz.md:Hint: `data.describe()`, and `target.value_counts()` are methods
jupyter-book/tuning/parameter_tuning_wrap_up_quiz.md:Hint: pass `{"preprocessor": all_preprocessors, "classifier__n_nei
```

**Comment by lfarhi** [comment]
I propose to add : "Remember that clicking on the Hint box is something you can do" just near "_Select several answers_" only when there is a Hint button. Is it ok for you ?

**Comment by ogrisel** [comment]
I think the hint button is useful to give hints that should not be necessary to correctly answer the question for most students who clearly understood the material, but could be helpful for students who failed to answer the question correctly at the first attempt for multiple choice questions.

However we should not use hidden hints for instructions that help the student avoid a usability trap of the scikit-learn API.

**Comment by lfarhi** [comment]
I replaced in FUN all the Hint buttons by a message below the proposals : "Hint: message"

**Comment by lesteve** [comment]
OK great, let's close this one then!
