### ISSUE TITLE
Small typo in parameter_tuning_ex_02.ipynb

### ISSUE THREAD

**Issue by albatros69** [INRIA/scikit-learn-mooc#354]
In exercise M3.01, there's a small type in the introduction text (2nd paragraph):
```
Here we use a small subset of the Adult Census dataset to make to code fast to execute. [...]
```
to be replaced by (or anything you feel more appropriate):
```
Here we use a small subset of the Adult Census dataset to make the code faster to execute. [...]
```

**Comment by lesteve** [comment]
Thanks a lot for your comment, this is now fixed!

Some small comments:
- not sure if you are following the ongoing MOOC session, but as a general rule of thumb, using the MOOC Discourse forum is preferrable. This way we use the Discourse forum for the MOOC feed-back and keep the github for our (more internal) organisation
- if you are not following the ongoing MOOC session and you are interested, you can register [here](https://www.fun-mooc.fr/en/courses/machine-learning-python-scikit-learn/). The course is free and you will get the full MOOC experience: videos, quizzes answers, Discourse forum for discussion/feed-back, and a JupyterHub so you don't have to install anything to run the notebooks

**Comment by albatros69** [comment]
Thanks for your quick reply!
I'm actually participating to the MOOC (which is really great!). As the github repo was public, I preferred this way of letting you know about issues. But I will use the forum next time, even if I'm not a great fan of the tool.
Sorry for the inconvenience,

**Comment by lesteve** [comment]
No worries and thanks a lot for the comment, this is just easier to handle user feed-back all in the same place (Discourse forum)!

> But I will use the forum next time, even if I'm not a great fan of the tool.

I was new to Discourse before the MOOC and I actually quite like it but yeah it is yet another tool that you have to get used to and that can be frustrating ... 

Just in case you have not discovered it yet: you can access the Discourse forum outside of the FUN-MOOC platform at this url: https://mooc-forums.inria.fr/moocsl/ (if you are logged in in FUN it should log you in automatically into Discourse)
