### ISSUE TITLE
Quiz Intro: question 3 and 4 should be single choice questions (and not multiple choices question)

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#360]
Let's keep this for v2 as most people get the answers correctly (OK they have 2 attempts instead of 1 but this is not a big deal):
https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session01/courseware/4594c1d8c9f847bdbc733c34d941c988/928e7401d2ed48a791036c555bca6d06/

![image](https://user-images.githubusercontent.com/1680079/120423096-069f8780-c36a-11eb-85ec-77192aee4a4a.png)

**Comment by lesteve** [comment]
ping @lfarhi @MarieCollin, this one should be changed on the FUN side for v2.

**Comment by lfarhi** [comment]
It's corrected in FUN

**Comment by lesteve** [comment]
OK great, thanks a lot, closing then!
