### ISSUE TITLE
Review quiz questions implying better/worse

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#366]
The questions based on the performance of the model and asking if a model is better/worse are too much of a headache. I think that we should rework this part. I would propose to:

- Add a lecture in the model evaluation to present a bit more in detail that cross-validation allows getting a distribution of the score. 
- We should then present intuitively the concept of formal "significance" with overlapping score distributions of two models.
- Finally, show what does it mean when we look at the mean and std. dev. of the score.
- Regarding the quizzes, I am not sure if we should either avoid making a comparison or provide a mechanical way (provide the formula to compute the score) to define that a model is better than another model. For sure we should make a new pass to check that all our questions are still right and do not depend on the random state :)

**Comment by lesteve** [comment]
Kind of related https://github.com/INRIA/scikit-learn-mooc/issues/304.

**Comment by lesteve** [comment]
Maybe useful to have a look at the worst quizz results: https://notes.inria.fr/rgSzYtubR6uSOQIfY9Fpvw#

**Comment by ogrisel** [comment]
There is one more MR in the private gitlab to finalize and after that this will be good.

**Comment by ArturoAmorQ** [comment]
I think now it's safe to close this issue, what do you think?
