### ISSUE TITLE
Glossary?

### ISSUE THREAD

**Issue by lucyleeow** [INRIA/scikit-learn-mooc#38]
Would it be useful to have a glossary. Maybe it could help with reminding people of terms and the terminology we use, e.g.,

here we state that we will use the terms 'hyper-parameter' and 'parameter' interchangably:

https://github.com/INRIA/scikit-learn-mooc/blob/adce6e0a9393be7d6e22fc393cdbdaf5698dda68/python_scripts/04_basic_parameters_tuning.py#L23

but this kind of thing may be easy to forget as you work through the material.

**Comment by glemaitre** [comment]
I think we had the discussion at some point. I might recall mentioning to link to the scikit-learn Glossary but this is really vague.

**Comment by lesteve** [comment]
IIRC the result of the discussion was that we need a glossary in the MOOC that would be more beginner oriented than the scikit-learn glossary.

**Comment by lesteve** [comment]
Terms that are used interchangably from #40.

-   estimator/learner/model
-   fit/learn/train
-   data point/sample/instance (i vote for not using instance, because we also talk about programming class instances)
-   infer/inference & predict/prediction
