### ISSUE TITLE
Bias-variance illustration using a dartboard

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#385]
There is a popular illustration of bias and variance using a dartboard (see [here](https://images.app.goo.gl/A4FY5BoHXAeuCCrS9) for instance) which gives an intuition of a 2-dimensional distribution. 

Is the phase (angle) of a given point to be taken seriously? 

In the case of the bias-variance trade-off does this 2 features have an interpretation? 

I have the feeling that this is just a cartoon and not to be taken literally.

**Comment by GaelVaroquaux** [comment]
> Is the phase (angle) of a given point to be taken seriously?

No

> In the case of the bias-variance trade-off does this 2 features have an interpretation?

No

> I have the feeling that this is just a cartoon and not to be taken literally.

Yes

**Comment by lesteve** [comment]
OK great I have to admit I asked myself a similar question at one point (and forgot what my conclusion was) so it's great to have some confirmation that this is only for illustration purposes.
