### ISSUE TITLE
Terminology consistency

### ISSUE THREAD

**Issue by lucyleeow** [INRIA/scikit-learn-mooc#40]
Might be a nitpick but I think being consistent in the terminology used in the notebook would be helpful for learners (the people :stuck_out_tongue: ). We should of course, note the other names something is called but for the notebooks be consistent. Potentially we could use terms that are consistent with those used in scikit-learn?

Off the top of my head these are used a little interchangeably:

* estimator/learner/model
* fit/learn/train
* data point/sample/instance (i vote for not using instance, because we also talk about programming class instances)
* infer/inference & predict/prediction

**Comment by glemaitre** [comment]
I think that we should solve this by using the glossary. It might be interesting to use (at least mentioned all known terms) related to the same concept.

**Comment by lesteve** [comment]
Closing in favour of a glossary #38. I put the terms mentioned by @lucyleeow there.
