### ISSUE TITLE
Slightly off vertical placement when using anchors in links on FUN

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#403]
@brospars input on this more than welcome! Wild-guess: could it be due to the fix of the weird scrolling in FUN on the left-hand side panel (I am reasonably sure it was working fine at one point ...)?

Go to the [glossary](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session01/fdb409a1a02a4e7497a2ff9533a496d1/#predict-prediction) and click on "predict":

![image](https://user-images.githubusercontent.com/1680079/126485248-1670823a-52cf-4c36-a38e-22ce062781a2.png)

This scrolls to:
![image](https://user-images.githubusercontent.com/1680079/126485302-44ec089a-9ba8-4c88-85ea-eea67cb472f8.png)

and I need to scroll-up a few lines to actually see the entry "predict". After scrolling up a bit:
![image](https://user-images.githubusercontent.com/1680079/126485560-affd825c-8870-4416-8709-fdbe677e09b3.png)

You can see that the "predict, prediction" entry and the first line was not visible before scrolling.

**Comment by brospars** [comment]
Yes it's related to the fix of the unwanted left-hand side panel scrolling... I removed smooth scrolling to fix unwanted scrolling outside of course content. That's what happen when you hack an app without a proper API, it often has unwanted side effects. Should be easy to fix.

**Comment by brospars** [comment]
Fixed.

**Comment by lesteve** [comment]
Nice, I doubled-check and with a hard refresh it work indeed, thanks a lot!

Do you have a commit diff somewhere for me to look at, I would love to be less dumb regarding this js magic ...

**Comment by lesteve** [comment]
This affects any anchor actually right? For example [this link](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session01/courseware/650bb3343e064e74a51923289d10ec6b/16bd0b44b0e14a918af81154bf4ca8f1/1?activate_block_id=block-v1%3Ainria%2B41026%2Bsession01%2Btype%40vertical%2Bblock%402f0ef0550f434df0a3c632b3054010c6#problem_3021f70aa91f481eac035aa390da1ae6)  is supposed to go to "Question 6" but actually ends up being a bit too low ...

**Comment by brospars** [comment]
It's a different problem. I capture anchor links being clicked not anchor in the URL. I'll take a look if that's doable despite my javascript being loaded last.

**Comment by lesteve** [comment]
OK to be honest, it is not such a big deal because MOOC users won't have this problem. 

For some context: I bumped into the last problem when trying to create links to particular quiz questions for convenience. We can very easily scroll up a few lines.

**Comment by lesteve** [comment]
Let's close this as good enough for now.
