### ISSUE TITLE
Introduce cross-validation earlier in module 1 and related changes

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#415]
- [x] 1. add a new notebook between the notebook 1 and 2 to introduce the model evaluation. It should discuss `train_test_split` and introduce `cross_validate`. This would be a notebook called something like "Evaluate your first model".
- [ ] 2. We would move some content from https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_scaling.html#model-evaluation-using-cross-validation but some discussions can be reduced since we don't use a `Pipeline` anymore.
- [ ] 3. If necessary, add a small section only speaking about the `Pipeline` inside `cross_validate` (I guess when this happens later in the "Preprocessing for numerical features" notebook
- [x] 4. "Exercise M1.03" -> check if we should add an additional exercise that uses cross-validation. Consensus: let's not add an exercise that may be too simple and distract from the main ideas.

**Comment by ArturoAmorQ** [comment]
I would add

5. Add discussion/plots on score distributions
6. Add [this figure](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png) illustrating cross-validation

**Comment by lesteve** [comment]
> Add discussion/plots on score distributions

If it is consise enough why not, I would have thought that module 2 was more the right place for a longer discussion (see https://github.com/INRIA/scikit-learn-mooc/issues/416). I guess we can quickly show here that the score depends on the train-test split which motivates the introduction of cross-validation

> Add this figure illustrating cross-validation

The figure you mention has things about hyperparameter tuning so we probably don't want to include this exact figure. We already have a cross-validation figure: https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_scaling.html#model-evaluation-using-cross-validation. If you think it can be improved (which is quite likely) you can look at the script generating the figure: https://github.com/INRIA/scikit-learn-mooc/blob/master/figures/plot_cross_validation_diagram.py

**Comment by ArturoAmorQ** [comment]
My idea / proposition for points 5. and 6. Notice that the distribution plot matches the example.

![CV](https://user-images.githubusercontent.com/86408019/129196389-6b6c7411-d114-48b6-a20d-8363bdcbfd4c.png)
![plot](https://user-images.githubusercontent.com/86408019/129197716-563c2d61-ce19-4c2f-b5b8-8793bd3ac3ac.png)

**Comment by lesteve** [comment]
I think most of this has been tackled.
