### ISSUE TITLE
Restructuring of module 2

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#416]
Split from #398:

The proposal of Arturo is good:
- [x] move score distribution and variations at the beginning of the module. covered by adding the video in M1:  https://inria.github.io/scikit-learn-mooc/predictive_modeling_pipeline/02_numerical_pipeline_video_cross_validation.html
- [ ] variability between 2 models
- [ ] and see the advancement of underfitting-overfitting, etc...

Also from https://github.com/INRIA/scikit-learn-mooc/issues/366:
- Add a lecture in the model evaluation to present a bit more in detail that cross-validation allows getting a distribution of the score. 
- We should then present intuitively the concept of formal "significance" with overlapping score distributions of two models.
- Finally, show what does it mean when we look at the mean and std. dev. of the score.

Also "The framework and why do we need it" is a weird title: https://inria.github.io/scikit-learn-mooc/python_scripts/cross_validation_train_test.html

**Comment by ArturoAmorQ** [comment]
> We should then present intuitively the concept of formal "significance" with overlapping score distributions of two models.

Piece of code to address this

```python
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

plt.rcParams["figure.figsize"] = (10,7)
plt.rcParams.update({'font.size': 16}) 
np.random.seed(12)

model_1 = pd.DataFrame([0.65,0.7,0.71,0.73,0.78],columns=['model_1'])
model_2 = list(np.random.normal(0.74, 0.07, 5))
model_2 = pd.DataFrame(model_2,columns=['model_2'])
models = pd.concat([model_1,model_2], axis=1)

bins=[0.6,0.64,0.68,0.72,0.76,0.8,0.84]
fig, ax1 = plt.subplots()
ax1.hist(models, bins=bins, label=['model_1', 'model_2'])
ax1.set_ylabel("frequency")
ax1.set_xlabel("test_score")
plt.tight_layout()
_ = plt.title("Overlapping score distributions")
```

Result:

![overlapping_plot](https://user-images.githubusercontent.com/86408019/129733149-c15b9016-5f44-44a5-b3d1-794178705baa.png)

Notice I used the same scores as in #415.

**Comment by ArturoAmorQ** [comment]
Maybe briefly mention how data can affect these distributions (data imbalance, for instance)

**Comment by lesteve** [comment]
Let's be honest I don't remember what this was about in details. Too generic issue like this tend to be less relevant with time, so I think we can close it.

By all means if someone remembers precisely what this was about, create a new issue with more info.
