### ISSUE TITLE
Idea about being more directive in wrap-up quiz to avoid coding variation giving the wrong answer

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#419]
Show pipeline `repr_html` and tell people your pipeline `repr_html` should look the same. This could potentially avoid problems like I used a OneHotEncoder (because why not after all) rather than a OrdinalEncoder and I don't get the same answer as the correction.

For complex pipelines this would be a bit like 7 difference game, so maybe a bit frustrating, to compare reference pipeline repr_html with . Also you probably need to click a lot around to expand fully the pipeline HTML, not super fun either.

**Comment by GaelVaroquaux** [comment]
> Also you probably need to click a lot around to expand fully the pipeline HTML,

We should be able to fix that, no?

**Comment by GaelVaroquaux** [comment]
> > Also you probably need to click a lot around to expand fully the pipeline HTML,

> We should be able to fix that, no?

I just understood: you meant for the student?

I think it's fine, the student will have patience :)

**Comment by lesteve** [comment]
Partially resolved by #361, moving this to 3.0

**Comment by lesteve** [comment]
Let's close this as not important enough
