### ISSUE TITLE
Add "uncertainty" to Glossary

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#426]
Even if we don't deal a lot with uncertainties, the term is mentioned a few times and adding it to the glossary may make the MOOC more self-contained. May also come handy when addressing  #416.

**Comment by lesteve** [comment]
I had a look and the place we use uncertainty are somewhat precise e.g. "uncertainty on the generalization accuracy".

Introducing a generic term in the glossary seems to complicated since there are many type of uncertainties.
