### ISSUE TITLE
First look at quizzes with worst scores

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#432]
I have started doing this at the very bottom of https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/blob/master/Bilans/detailed_quiz_results_analysis.py but I am not planning to work on it before the v1 feed-back meeting in September.

rendered notebook: https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/blob/master/Bilans/detailed_quiz_results_analysis.ipynb

Note: you can look at the all the quiz answers with this URL:
https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session01/fun/dashboard/problem_stats/index/

If you want a link to a particular question results, you can use "open in new tab" for example the answers for Quiz M4.04b Question 3:
https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session01/fun/dashboard/problem_stats/get_stats/e545a10b08b5413e9b8d384b0be9f007

(the green color showing the right answers as well as some table formatting are gone in the per-question link)

**Comment by lesteve** [comment]
I put the quiz results analysis in a pad to make collaboration easier: https://notes.inria.fr/rgSzYtubR6uSOQIfY9Fpvw#

**Comment by lesteve** [comment]
Need to check the wrap-up quizzes for the score < 60%.

The quizzes 60% < score < 70% can probably be left for 3.0.

**Comment by ArturoAmorQ** [comment]
Now that we merged [!62](https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/62) we have addressed all the questions with score below 60%. I think it's safe to close this issue now.
