### ISSUE TITLE
Add figure illustrating nested cross-validation

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#433]
The first time the concept of *nested cross-validation* appears is in M3 [here](https://inria.github.io/scikit-learn-mooc/python_scripts/parameter_tuning_nested.html), then in M4 [here](https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_regularization.html) and is later covered more in detail in M7. Adding a figure similar to [this one](https://mlfromscratch.com/content/images/2019/12/ncv.png) would visually improve the concept.

Some options are: 
- Add the figure in M3 and refer to it in M7
- Add the figure in M7 and mention in M3 that this topic will be later covered in detail

What do you think?

**Comment by ArturoAmorQ** [comment]
The MOOC forum post is this one

https://mooc-forums.inria.fr/moocsl/t/suggestion-presenting-nested-cross-validation/4418

**Comment by ArturoAmorQ** [comment]
Here is a suggested figure following the conventions in [this image](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png). It chooses an inner loop that exactly divides the outer-loop testing-folds for the sake of clarity, but we would have to specify that this is not the most general case...

There is most surely space for improving the figure, so any comments are more than welcome!

![nested-cv](https://user-images.githubusercontent.com/86408019/131879129-e5f5859d-f88b-409c-823f-33bf874334ef.png)

**Comment by lesteve** [comment]
I bumped into a figure I find clearer from:
https://raw.githubusercontent.com/mlr-org/mlr3book/main/bookdown/images/nested_resampling.png

![image](https://user-images.githubusercontent.com/1680079/133398526-6842e08d-931a-49ba-a7ae-b094f761be2e.png)

I am not too sure about the block-like structure (the full data is separated into 6 discrete blocks), maybe removing these blocks would be clearer. Alternatively mention the number of outer and inner folds.

**Comment by lesteve** [comment]
This has been done in the nested_cross_val notebook.
