### ISSUE TITLE
Accessing coefficients inside a pipeline

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#435]
Extracting information from a given step inside a pipeline can be tricky and is not explained -yet used- along the MOOC (See [this post in the forum](https://mooc-forums.inria.fr/moocsl/t/coefficients-in-pipeline/4793)).

One possible solution is to rewrite solutions to use more straightforward code 

Another possibility is compatible with #415:

> If necessary, add a small section only speaking about the Pipeline inside cross_validate (I guess when this happens later in the "Preprocessing for numerical features" notebook

What do you think?

**Comment by lesteve** [comment]
To be included in the model inspection module #124

**Comment by ArturoAmorQ** [comment]
I think a link to https://scikit-learn.org/stable/modules/compose.html#usage may suffice.

**Comment by ogrisel** [comment]
Once #710 and #723 are merged, we can probably close this issue.
