### ISSUE TITLE
jupyter notebook cell output not saved and not shown in build

### ISSUE THREAD

**Issue by Zethson** [INRIA/scikit-learn-mooc#438]
Hi,

thank you for the great work. I want to build the book myself, but unfortunately the cell output is not showing.
Steps: 
1. Create conda environment with dev environment
2. Execute `make jupyter-book` without any errors
3. Open html files in `jupyter-book/_build/html`.

The cells executions did not get saved:
![image](https://user-images.githubusercontent.com/21954664/129573058-b90810f6-d4de-4f1d-8f43-68d7a81bdc8e.png)

When I opened the notebooks in the notebooks folder they look like they were never executed.
What am I doing wrong?

Thanks!

**Comment by Zethson** [comment]
Ahh, I had to run `make jupyter-book-full-clean` first. Then building it again worked. Why is that?

**Comment by Zethson** [comment]
```
⋊> /t/scikit-learn-mooc on master ⨯ make all                                                                                                                                   (base) 16:24:31
cp python_scripts/matplotlibrc notebooks/
python build_tools/sanity-check.py python_scripts notebooks
⋊> /t/scikit-learn-mooc on master ⨯ make                                                                                                                                       (base) 16:24:32
cp python_scripts/matplotlibrc notebooks/
python build_tools/sanity-check.py python_scripts notebooks
⋊> /t/scikit-learn-mooc on master ⨯ make notebooks                                                                                                                             (base) 16:25:03
cp python_scripts/matplotlibrc notebooks/
python build_tools/sanity-check.py python_scripts notebooks
```

I am also confused by this output. Shouldn't these commands be doing something instead of just printing this stuff out?

**Comment by lesteve** [comment]
Sorry we have missed this one. Glad you got it working at the end. For now the build is kind of an internal thing and it may change without notice.
