### ISSUE TITLE
KBinsDiscretizer drastically reduced fit time

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#443]
This [post in the forum](https://mooc-forums.inria.fr/moocsl/t/discretizer-drastically-reduced-fit-time/4237) complains about the use of the word _drastically_ in [this notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/ensemble_hist_gradient_boosting.html) for describing the improvement of using `KBinsDiscretizer` along with `GradientBoostingRegressor`. 

That paragraph could be rephrased not only to suppress the word _drastically_ but also to include [Olivier's detailed answer](https://mooc-forums.inria.fr/moocsl/t/discretizer-drastically-reduced-fit-time/4237/5) on the `nlog(n)` vs. linear complexity when introducing `HistGradientBoostingRegressor`.

What do you think?

**Comment by ArturoAmorQ** [comment]
There is another [post in the forum](https://mooc-forums.inria.fr/moocsl/t/kbinsdiscretizer-in-speeding-up-gradient-boosting-lesson-i-do-not-understand-your-sentence/4234) complaining about the use of the word _integer_ in the same notebook. This can also be fixed without too much effort.

**Comment by ogrisel** [comment]
Given that this is part of an advanced module I think it's ok to include a "note" block with such "advanced" remarks on computational complexity.
