### ISSUE TITLE
Add video showing how to select a range of results in a parallel coordinate plot

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#447]
Following Guillaume's suggestion in [this forum comment](https://mooc-forums.inria.fr/moocsl/t/video-to-explain-how-to-use-the-interactive-parallel-coordinates-plot/2548/4), a video after [this notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/parameter_tuning_randomized_search.html) showing how to select a range of results in a parallel coordinate plot may suffice to complement the explanation on how to use this tool.

This may also improve the scores for Quiz M3.2 Q4 and Q5, which are both below 70%.

**Comment by ogrisel** [comment]
+1

If you write down the script I can give you a review before the recording. Otherwise we can review a draft video.

**Comment by ogrisel** [comment]
I sorry you already posted the video on mattermost. I thought it was a new version of the previous one. Let me review it now.

**Comment by ogrisel** [comment]
About the actual content of the video I find it nice and informative and should be good to address the feedbacks on the forum for this module quiz questions.

**Comment by ArturoAmorQ** [comment]
> If you write down the script I can give you a review before the recording. 



```python

import pandas as pd

cv_results = pd.read_csv("../figures/randomized_search_results.csv",
                         index_col=0)
```

```python
cv_results.head()
```

```python
def shorten_param(param_name):
    if "__" in param_name:
        return param_name.rsplit("__", 1)[1]
    return param_name
```

```python
(cv_results.rename(
    shorten_param, axis=1).sort_values("mean_test_score", ascending= False)).head()
```

```python
import numpy as np
import plotly.express as px

fig = px.parallel_coordinates(
    cv_results.rename(shorten_param, axis=1).apply({
        "learning_rate": np.log10,
        "max_leaf_nodes": np.log2,
        "max_bins": np.log2,
        "min_samples_leaf": np.log10,
        "l2_regularization": np.log10,
        "mean_test_score": lambda x: x}),
    color="mean_test_score",
    color_continuous_scale=px.colors.sequential.Viridis,
)
fig.show()
```

**Comment by ogrisel** [comment]
```
(cv_results.rename(
    shorten_param, axis=1).sort_values("mean_test_score", ascending= False)).head()
```

can be simplified to:

```python
cv_results.rename(shorten_param, axis=1)
```

as the goal of this cell is just to demo the renaming function, not to analyze the resulting scores if I am not mistaken

**Comment by ArturoAmorQ** [comment]
> as the goal of this cell is just to demo the renaming function, not to analyze the resulting scores if I am not mistaken

Indeed, you are right!
