### ISSUE TITLE
Suggestion for linear notebook

### ISSUE THREAD

**Issue by TwsThomas** [INRIA/scikit-learn-mooc#45]
This suggestions come from the PR #37 :

- [x] We use the terms formula/formulate, rule and model (sometimes a bit interchangeably) but we never explicitly explain the relationship between them/what a model is e.g., a model is a formula for relating features to target. We do talk about it a bit in the first notebook but it's not clearly relating 'model' to 'rule':
https://github.com/INRIA/scikit-learn-mooc/blob/master/python_scripts/01_tabular_data_exploration.py#L202-203

- [x] We switch between using the terms infer/inference & predict/prediction. This is a nitpick but I think we should consistently only
use one term or explain that they mean the same thing.

- [x] Might not be necessary but should we clarify that curve just means 'line' and does not need to be curved, i.e., can be a straight line?

- [x] (l.352) Shall we already talk about kernel here ? In this case it might require more description of what a kernel is. Also more description on 'decision function' would be nice too.

- [ ] (l866) Would it be worth giving the logistic regression model equation or explaining more about these coefficients?

**Comment by glemaitre** [comment]
The last point will be decided when we will further review the notebook
