### ISSUE TITLE
Avoid use of l2 penalty/l2 regularization

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#451]
Even if we have a section _Regularization in linear model_ where we present  `Ridge`'s alpha and `LogisticRegression`'s C to introduce the concept of regularizing parameters, we don't really go into the mathematical background of l1 and l2 regularizations. We may want to avoid introducing concepts to keep things as simple as possible.

Variants of the term l2 penalty/l2 regularization are used in the following notebooks:

- [Hyperparameter tuning by randomized-search](https://inria.github.io/scikit-learn-mooc/python_scripts/parameter_tuning_randomized_search.html) referring to the hyperparameter in `HistGradientBoostingClassifier`. This is fine as it is regarded as another hyperparameter and a simple explanation is provided. 
- [Quiz M3.02](https://inria.github.io/scikit-learn-mooc/tuning/parameter_tuning_automated_quiz_m3_02.html) also referring to the hyperparameter in `HistGradientBoostingClassifier`. This is also fine as it is the sequence of the randomized-search notebook.
- [Solution for Exercise M4.04](https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_sol_04.html) mentioned inside a _Tip message_ referring to the general use of regularizing parameters such as `Ridge` alpha and `LogisticRegression` C. This can easily be rephrased.
- [Quiz M4.04b](https://inria.github.io/scikit-learn-mooc/linear_models/linear_models_quiz_m4_04b.html) referring to Ridge alpha. Notice that Q1 and Q5 are too similar. We could merge them and use simply "alpha" instead.
- [Exercise M4.05](https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_ex_05.html) and [its solution](https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_sol_05.html) set `penalty="l2"` in the argument of the `LogisticRegression`. This can be suppressed as it is already the default penalty for this classifier.

- [Quiz M4.05](https://inria.github.io/scikit-learn-mooc/linear_models/linear_models_quiz_m4_05.html) asks if the default setting of the `LogisticRegression` is a) no penalty;  b) a l2 penalty;  c) a l1 penalty. We can appeal to the C parameter only, has the l1 penalty is not mentioned elsewhere in the MOOC.

As elsewhere in the MOOC we either use alpha or C, accordingly, I suggest we change l2-regularization -> regularization and avoid appealing to "l2" before an hypothetical module on feature selection. What do you think?

**Edit:** Another option (as discussed with Guillaume) is to add a small description explaining that both alpha (for `RidgeCV`) and  C (for `LogisticRegression`) are examples of a broader category of hyperparameters.

**Comment by glemaitre** [comment]
I think that @GaelVaroquaux will be strongly against this proposal. Indeed, for machine learning, we should always use L2 regularization. Here, I think that we don't go first in detail regarding this aspect. We only use a non-regularized model to present the basics of the linear model and then give an example to show that one should not do that in practice.

**Comment by ogrisel** [comment]
The problem is not about not using regularization but about mentioning "l2 regularization" instead of just "regularization" since we do not explain what "l2" stands for and don't want to do it, at least not at the beginning of the MOOC.

> As elsewhere in the MOOC we either use alpha or C, accordingly, I suggest we change l2-regularization -> regularization and avoid appealing to "l2" before an hypothetical module on feature selection. What do you think?

I am fine with that.

> Edit: Another option (as discussed with Guillaume) is to add a small description explaining that both alpha (for RidgeCV) and C (for LogisticRegression) are examples of a broader category of hyperparameters.

I am fine with that approach as well. Maybe we can do both to some extent.
