### ISSUE TITLE
Increase plot size or font size whenever needed

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#457]
As mentioned by Gaël, some plots could have better readability after increasing either their size or font size.

One example is the [Solution for Exercise M6.02](https://inria.github.io/scikit-learn-mooc/python_scripts/ensemble_sol_02.html), where the labels overlap the plot.

This is a nice-to-have but not a priority for v2.

**Comment by glemaitre** [comment]
Regarding the font size, I think that we are fine we this file: https://github.com/INRIA/scikit-learn-mooc/blob/master/python_scripts/matplotlibrc

So in the notebook and jupyter-book, it will be OK. It is true that some of the figures would benefit either from a slight increase or sometimes move the legend outside of the figure. I think that this second point should always be considered with the amount of matplotlib code that such change will involve.

**Comment by lesteve** [comment]
TODO: put a list of problematic figures

**Comment by ogrisel** [comment]
Putting the legends outside the figures improved things a lot so the problem can be considered solved generally.

Once could still review all figures to generally increase the figure sizes overall. But at least they are readable enough now.
