### ISSUE TITLE
Consistent British or American spelling

### ISSUE THREAD

**Issue by lucyleeow** [INRIA/scikit-learn-mooc#48]
See https://github.com/INRIA/scikit-learn-mooc/pull/39#discussion_r469912340

I understand the default on the internet seems to be American spelling (even though it is wrong :roll_eyes: )

**Comment by GaelVaroquaux** [comment]
> I understand the default on the internet seems to be American spelling

American!

> (even though it is wrong 🙄 )

I don't know how to write the kiwi accent.

**Comment by lesteve** [comment]
Agreed, we should try to aim for American spelling.
