### ISSUE TITLE
Update `plot_decision_function` to a display

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#485]
For the moment #484 does the job of getting rid of the UserWarnings. But we should consider updating the function for plotting a classifier decision function to a display: 

https://github.com/glemaitre/datascience_middle_course/blob/main/02_linear_models/helper/plotting.py#L59

_Originally posted by @glemaitre in https://github.com/INRIA/scikit-learn-mooc/pull/484#r745848707_

**Comment by glemaitre** [comment]
Done
