### ISSUE TITLE
Rename intro notebooks

### ISSUE THREAD

**Issue by ogrisel** [INRIA/scikit-learn-mooc#5]
I find the current names not descriptive enough. I think we should rename "basic" to "intro" in general and more specifically:

- 02_basic_preprocessing => 02_numerical_pipeline
- 03_basic_categorical_variables => 03_categorical_pipeline
- 04_basic_parameter_tuning => 04_parameter_tuning

For the exercises & solutions we could shorten the names to something like:

- 02_numerical_pipeline_E01.ipynb
- 02_numerical_pipeline_S01.ipynb

The lexicographical order should still be good.

**Comment by lesteve** [comment]
Sorry missed that (I was not watching the inria/scikit-learn-mooc repo ...). No strong opinion.

The thing I remember is that it is slightly painful to rename things, because you need to:
- rename `.py` (including exercises)
- rename `.ipynb` (including exercises)
- change `jupyter --set-formats` to pair the right filenames
- maybe more things I forgot about ...

**Comment by ogrisel** [comment]
This should be simpler now:

- rename .py files
- update `jupyter-book/_toc.yml`
- run make
- check that everythink looks alright, maybe delete old files that are no longer used.

**Comment by lesteve** [comment]
I ended up putting together a hacky `.ipy` file (i.e. need to be executed with `ipython` or inside a notebook since I am using `!` to execute `git mv` bash commands inside).

Putting it here in case it can be useful for some other bulk renaming in the future.

```py
import re
import glob
import os

files = (
    [f for f in glob.glob('python_scripts/*') if os.path.basename(f).startswith('0')] +
    [f for f in glob.glob('notebooks/*') if os.path.basename(f).startswith('0')] +
    [f for f in glob.glob('jupyter-book/*/*.md') if os.path.basename(f).startswith('0')]
)

print(files)

replacement_dict = {
    '02_basic_preprocessing': '02_numerical_pipeline',
    '03_basic_preprocessing_categorical_variables': '03_categorical_pipeline',
    '04_basic_parameters_tuning': '04_parameter_tuning',
    r'exercise_(\d\d)_solution': r'sol_\1',
    'exercise_': 'ex_',
}

def translate(text, replacement_dict):
    t = text
    for key, value in replacement_dict.items():
        t = re.sub(key, value, t)
    return t

for fn in files:
    new_fn = translate(fn, replacement_dict)
    if fn != new_fn:
        !git mv $fn $new_fn

toc_fn = 'jupyter-book/_toc.yml'

with open(toc_fn) as f:
    content = f.read()
    new_content = translate(content, replacement_dict)

with open(toc_fn, 'w') as f:
    f.write(new_content)
```
