### ISSUE TITLE
Issue on page /ml_concepts/slides.html

### ISSUE THREAD

**Issue by sudheerkopparapu** [INRIA/scikit-learn-mooc#502]
Unable to view slides properly. No options to control or go to next slide.

**Comment by glemaitre** [comment]
This is not user friendly as expected. To control slides navigation you need to first click on the slides and then use the arrow right/left. We will look at how to solve the issue.

**Comment by lesteve** [comment]
The remark API is here: https://github.com/gnab/remark/wiki/Configuration#api. We have disabled scroll in https://github.com/INRIA/scikit-learn-mooc/blob/7a3200cb827286746529bd91ba16e110375ff2ac/slides/index.html#L13-L26 to avoid weird issues in FUN (scrolling scrolls the page and then switch to scrolling the slides or maybe both at the same time I don't remember exactly) but maybe we can enable click (not sure what it does)

**Comment by ogrisel** [comment]
The CSS stylesheet for the iframes (videos and slides) have been revamped and I put instructions on how to navigate the slides below them.

Closing. Feel free to reopen a new issue with more details if it still does not work for you.
