### ISSUE TITLE
Find a good place for the video on jupyter notebook shortcuts

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#519]
Following today's discussion, there are 2 options for placing the jupyter shortcuts video:

1- Between the [First look at our dataset notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/01_tabular_data_exploration.html) and [Exercise M1.01](https://inria.github.io/scikit-learn-mooc/python_scripts/01_tabular_data_exploration_ex_01.html). This was the original intention, as the video says things like "this is the very first cell of code that you had to run".

2- In the Welcome section of the FUN platform only. The reason being that the beginning of the video shows how to maximize the jupyter notebook inside FUN and then it would feel a bit awkward to mention it in the static version.

What do you think?

**Comment by ogrisel** [comment]
I think 2 (in the FUN welcome section of the scikit-learn MOOC) is more natural, although some people might skip it.

But I am not opposed to 1 either.

**Comment by glemaitre** [comment]
When discussing during the meeting, it looks like a good idea to do 2.

**Comment by lesteve** [comment]
If we think this is important, we can always add a link in FUN at the top of the page of Exercice M1.01 saying "don't forget to check this video about Jupyter tips and tricks if you haven't already done so".

**Comment by lfarhi** [comment]
I placed the video:
- In the Welcome section of the FUN platform only, after the lecture "Getting started with Jupyter" : [here](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/91dbf6b507694e62804ab006427dff25)
-  I added a link to the video at the top of the page ["First look at our dataset"](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/0194c5153693497b8cc3f7c9122b494c)

![Lecture: First look at our dataset | Tabular data exploration | Contenu du cours 41026 | FUN-MOOC 2022-01-18 17-20-12](https://user-images.githubusercontent.com/4948988/149977004-6b61f7a7-7c07-4539-a1b2-224fa9691ade.png)
 
Tell me if it's ok for you

**Comment by ArturoAmorQ** [comment]
I would add a line break before "if you are not familiar ..." and I think it would be better to say "watch the video" instead of "look at the video". Apart from that I like the placements! Thanks!

**Comment by lfarhi** [comment]
Thanks @ArturoAmorQ , it's done : https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/0194c5153693497b8cc3f7c9122b494c

**Comment by ArturoAmorQ** [comment]
Thank you @lfarhi
