### ISSUE TITLE
Issue on page /tuning/parameter_tuning_parallel_plot_video.html

### ISSUE THREAD

**Issue by lfarhi** [INRIA/scikit-learn-mooc#531]
Ce serait bien d'avoir le même titre que dans la vidéo c'est à dire : "Hyperparameter tuning visualization" plutôt que "Interactive exploration of hyper-parameter search results" qui est très long.

**Comment by ogrisel** [comment]
Est-ce que "Analysis of hyper-parameter search results" serait assez court? Je trouve que "Hyperparameter tuning visualization" n'est pas tres descriptif.

**Comment by ArturoAmorQ** [comment]
Il s'agit surtout du titre qui doit être identique à celui de la vidéo, n'est pas?. 
Je pense que ne pas être assez descriptif avec un titre est toujours un problème dans une certaine mesure.

**Comment by ogrisel** [comment]
Je pense que c'est pas un probleme d'ameliorer le titre dans le jupyter notebook si celui de la video est suboptimal (mais pas la peine d'editer / reenregistrer la video pour ca).

**Comment by lfarhi** [comment]
Alors ok pour "Analysis of hyper-parameter search results" dans le JupyterBook et dans FUN. 
On modifiera plus tard le titre dans la vidéo.

**Comment by MarieCollin** [comment]
Les vidéos dans leurs versions d'origine sont sur la playlist youtube dans l'ordre du Jupyterbook : https://www.youtube.com/playlist?list=PL2okA_2qDJ-m44KooOI7x8tu85wr4ez4f
Les corrections dans les vidéos elle-mêmes ne sont donc pas intégrées.
Pour le partage de la dernière vidéo en 2 (ensemble: bagging / ensemble: boosting), merci de déposer sur mybox quand elles sont prêtes : https://mybox.inria.fr/d/150036e793c546a1bdfd/
