### ISSUE TITLE
Video to show how to use the red "Open notebook" button in FUN

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#533]
I made a short video to address the second point of #369.

https://www.dropbox.com/s/7vey1b4uc5igchr/2022-01-12-14-58-26.webp

The options are:
1- Add it below the last bullet point of either the first or every wrap-up quiz (see image below).
2- Add it to the "How to use the FUN Platform?" section of the "Welcome" module.

The downside of 1- is that it might be too distracting, and the downside of 2- is that it would be easy to omit it completely.

![wrap-up](https://user-images.githubusercontent.com/86408019/149157881-e2456ebe-364a-4615-a347-c0cd2d6f623e.png)

**Comment by ArturoAmorQ** [comment]
@lesteve suggested making the video foldable (and probably folded by default).

> I would add to the last bullet point something like "look at this short gif for more details" and when you click on "short gif" you see the gif (and you can hide it again by clicking on the same button). 

But then we risk the hidden video to be overlooked at.

**Comment by ArturoAmorQ** [comment]
@lfarhi, what do you think? which option is easier/more optimal?

**Comment by lesteve** [comment]
> But then we risk the hidden video to be overlooked at.

Life is about trade-offs :wink: ...

**Comment by lfarhi** [comment]
_The options are:
1- Add it below the last bullet point of either the first or every wrap-up quiz (see image below).
2- Add it to the "How to use the FUN Platform?" section of the "Welcome" module._

1- I added a paragraph about wrap-up quizzes in the "How to use the FUN Platform?", with the animation :
https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/7f34ea542bcd493f86eee66dcdf89ed3#wp-quizzes 

2- For every wrap-up quiz, I propose 2 solutions (see https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/8ac8c1bec30a474aac36e9c05ba229df to look both):
- an item "click here for an animated demo"
- make the animation foldable with the label "> See an animated demo"
Which one do you prefer ?

**Comment by ArturoAmorQ** [comment]
I like the double solution. Thanks!

**Comment by MarieCollin** [comment]
option bullet point: 
+ fait partie de la liste des indications
- on ne sait plus où on est après avoir vu la vidéo

option plier/déplier:  +/- opposés à l'option bullet point

Sinon "a demo video of the notebook user interface" plutôt que "an animated demo" pour être plus explicite ?

**Comment by lfarhi** [comment]
New proposal:
![Wrap up quiz 1 | Wrap-up quiz | Contenu du cours 41026 | FUN-MOOC 2022-01-21 12-27-01](https://user-images.githubusercontent.com/4948988/150519455-6d51bd24-e678-403b-8761-eeb30167cdef.png)

**Comment by ArturoAmorQ** [comment]
The new proposal LGTM

**Comment by lfarhi** [comment]
Dernière proposition:
- [Wrapup quiz 1](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/8ac8c1bec30a474aac36e9c05ba229df) --> déplié à l'affichage
![Wrap up quiz 1 | Wrap-up quiz | Contenu du cours 41026 | FUN-MOOC 2022-01-24 11-13-20](https://user-images.githubusercontent.com/4948988/150764129-e673895e-0c85-40d8-a1b0-dbe7c32e352b.png)

- [Wrapup quiz 2-7](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/2f0ef0550f434df0a3c632b3054010c6) --> plié à l'affichage
![Wrap-up quiz 2 | Wrap-up quiz | Contenu du cours 41026 | FUN-MOOC 2022-01-24 11-13-51](https://user-images.githubusercontent.com/4948988/150764172-0bef4b39-8dd5-45e7-8f74-ac65d5d139ad.png)

**Comment by ArturoAmorQ** [comment]
Did the legend and red coloring of the "Click here to see a demo video of the notebook user interface" message changed in the last version? I like the former the best.

Apart from that, having the video unfolded on display for the first time and folded for the rest of the wrap up quizzes is alright.

**Comment by lfarhi** [comment]
Do you prefer this for [Wrapup quiz 2-7](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/2f0ef0550f434df0a3c632b3054010c6)

![Wrap-up quiz 2 | Wrap-up quiz | Contenu du cours 41026 | FUN-MOOC 2022-01-24 12-14-58](https://user-images.githubusercontent.com/4948988/150773156-6a7cd8ac-d1b2-48ee-9093-65be09cc60a9.png)

**Comment by ArturoAmorQ** [comment]
> Do you prefer this for [Wrapup quiz 2-7](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/2f0ef0550f434df0a3c632b3054010c6)

Yes, LGTM

**Comment by lfarhi** [comment]
👌
