### ISSUE TITLE
"select several answers" on page /ensemble/ensemble_quiz_m6_01.html

### ISSUE THREAD

**Issue by lfarhi** [INRIA/scikit-learn-mooc#536]
Question 1 et 2 : doit-on ajouter <i>Select several answers</i> ou remplacer par une question à choix unique ?

**Comment by glemaitre** [comment]
We are going to open a meta-issue where we will point out all the places where we want to add "multiple/single choice" info.

Basically, we want to add this note everywhere to be consisent.

**Comment by ogrisel** [comment]
@glemaitre I find the phrasing "select several answers" problematic. I think it should be "select one or more answers" for multiple choice questions.

**Comment by lfarhi** [comment]
@ogrisel , I agree, "select several answers" is ambiguous. We may also used "Several answers possible".

**Comment by ogrisel** [comment]
+1 for "Several answers possible".

**Comment by ogrisel** [comment]
- "Select a single answer"
- "Several answers possible"

**Comment by lesteve** [comment]
Closing this one in favour of #546.
