### ISSUE TITLE
404 for the sandbox notebook in the menu of the session2

### ISSUE THREAD

**Issue by ogrisel** [INRIA/scikit-learn-mooc#540]
The session 2 menu entry points to the following URL:

https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/ac2e8d103d084cfda713123163f7a9a8/

but I get a 404 error when clicking on it.

/cc @brospars

**Comment by lfarhi** [comment]
It's corrected

**Comment by ArturoAmorQ** [comment]
Thanks!
