### ISSUE TITLE
Figures in quiz M7.04, Question 2

### ISSUE THREAD

**Issue by lfarhi** [INRIA/scikit-learn-mooc#543]
In FUN, We can't have figures in the question. So I had to modify Question 2 of [M7.04 Quiz](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/jump_to_id/640742bb742c4dd4a16a96e5821730c2).

Tell me if it's ok for you (captures below)

<img width="839" alt="Quiz M7 04 | Classification metrics | Contenu du cours 41026 | FUN-MOOC 2022-01-19 14-04-09" src="https://user-images.githubusercontent.com/4948988/150136267-1157addd-396d-4c24-8c05-d7280a9fddef.png">

<img width="863" alt="Quiz M7 04 | Classification metrics | Contenu du cours 41026 | FUN-MOOC 2022-01-19 14-04-29" src="https://user-images.githubusercontent.com/4948988/150136247-58eb7a8a-219c-47e6-85bb-a02d741f7de2.png">

**Comment by ArturoAmorQ** [comment]
LGTM except that there was an extra "the" in the instructions "select the which statements". I fixed it in both gitlab and github.

**Comment by lfarhi** [comment]
Thanks @ArturoAmorQ , it's corrected
