### ISSUE TITLE
Add Discourse voting plugin or alternatives?

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#544]
https://meta.discourse.org/t/discourse-voting/40121

This may help prioritising which questions to answer in the forum. 

Reading a bit more, there may be caveats:
- 10 active votes by default (which you get back when topics are archived or closed which we don't use), we should probably make it a lot higher maybe 100?
- enabling votes on a category disables likes, is it important? There seems to be a way to reactivate likes with CSS: 
https://meta.discourse.org/t/show-both-like-and-vote-button-on-topics/101252/2
- is there an easy way to sort topics by most voted?

An alternative way would be to show other proxies for interests in the "latest" page, e.g. views or likes.
It seems this does a bit what we want (op_likes is on the top post which is probably what we want):
https://mooc-forums.inria.fr/moocsl/?order=op_likes

from: https://meta.discourse.org/t/display-like-counts-on-home-page-topic-list/58742. There are other suggestions to add a likes column in the latest page which may be useful.

**Comment by ogrisel** [comment]
I agree I think that would be really helpful to help us focus on the important pending problems reported by mooc participants.

**Comment by lesteve** [comment]
I think the good-enough solution would be to have number of views and number of op_likes (likes of the top post) in the home page.

**Comment by lesteve** [comment]
Let's revisit this for v3, we can use https://mooc-forums.inria.fr/moocsl/?order=op_likes as a good enough proxy if we want to answer the questions with the most interest.

**Comment by lesteve** [comment]
Not important enough, let's close this one.
