### ISSUE TITLE
Harmonise single choice question vs multiple choice question

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#546]
We should have annotations everywhere for consistency and to help putting the quizzes in FUN:

The consensus is:
- "Select a single answer" => Unique choice question
- "Select all answers that apply" => Multiple-select question

The problematic quizzes:
- [x] jupyter-book/ensemble/ensemble_quiz_m6_01.md 1 guidances != 3 questions
- [x] jupyter-book/ensemble/ensemble_quiz_m6_02.md 2 guidances != 4 questions
- [x] jupyter-book/ensemble/ensemble_quiz_m6_03.md 2 guidances != 3 questions
- [x] jupyter-book/evaluation/evaluation_quiz_m7_01.md 0 guidances != 3 questions
- [x] jupyter-book/evaluation/evaluation_quiz_m7_02.md 0 guidances != 1 questions
- [x] jupyter-book/evaluation/evaluation_quiz_m7_03.md 0 guidances != 1 questions
- [x] jupyter-book/evaluation/evaluation_quiz_m7_04.md 0 guidances != 2 questions
- [x] jupyter-book/evaluation/evaluation_quiz_m7_05.md 0 guidances != 4 questions
- [x] jupyter-book/evaluation/evaluation_wrap_up_quiz.md 10 guidances != 11 questions
- [x] jupyter-book/feature_selection/feature_selection_quiz.md 1 guidances != 2 questions
- [ ] jupyter-book/interpretation/interpretation_quiz.md 0 guidances != 5 questions (not doing this one, this module is WIP)
- [x] jupyter-book/linear_models/linear_models_quiz_m4_01.md 2 guidances != 3 questions
- [x] jupyter-book/linear_models/linear_models_quiz_m4_02.md 0 guidances != 2 questions
- [x] jupyter-book/linear_models/linear_models_quiz_m4_03.md 0 guidances != 2 questions
- [x] jupyter-book/linear_models/linear_models_quiz_m4_04.md 1 guidances != 5 questions
- [x] jupyter-book/linear_models/linear_models_quiz_m4_05.md 0 guidances != 3 questions
- [x] jupyter-book/ml_concepts/quiz_intro_01.md 0 guidances != 4 questions
- [x] jupyter-book/overfit/bias_vs_variance_quiz_m2_03.md 0 guidances != 2 questions
- [x] jupyter-book/overfit/learning_validation_curves_quiz_m2_02.md 0 guidances != 6 questions
- [x] jupyter-book/overfit/overfit_wrap_up_quiz.md 7 guidances != 9 questions
- [x] jupyter-book/predictive_modeling_pipeline/01_tabular_data_exploration_quiz_m1_01.md 1 guidances != 4 questions
- [x] jupyter-book/predictive_modeling_pipeline/02_numerical_pipeline_quiz_m1_02.md 1 guidances != 7 questions
- [x] jupyter-book/predictive_modeling_pipeline/03_categorical_pipeline_quiz_m1_03.md 0 guidances != 4 questions
- [x] jupyter-book/trees/trees_quiz_m5_02.md 0 guidances != 3 questions
- [x] jupyter-book/trees/trees_quiz_m5_03.md 0 guidances != 3 questions
- [x] jupyter-book/trees/trees_quiz_m5_04.md 0 guidances != 2 questions
- [x] jupyter-book/tuning/parameter_tuning_automated_quiz_m3_02.md 2 guidances != 5 questions
- [x] jupyter-book/tuning/parameter_tuning_manual_quiz_m3_01.md 0 guidances != 4 questions

which I got through this code:
```py
import re
from pathlib import Path

repo_path = Path('~/dev/mooc-scikit-learn-coordination').expanduser()
jupyter_book_path = repo_path / 'jupyter-book'
quiz_paths = sorted(jupyter_book_path.glob('*/*quiz*.md'))

for p in quiz_paths:
    content = p.read_text()
    num_question_guidances = len(re.findall(r'_select.+answer|_several answers possible', content, re.IGNORECASE))
    num_questions = len(re.findall('{admonition}', content))

    if num_question_guidances != num_questions:
        rel_path = p.relative_to(repo_path)
        print(f'{rel_path} {num_question_guidances} guidances != {num_questions} questions')
```

**Comment by lesteve** [comment]
I pushed directly a commit for the two wrap-up quizzes since that was not interfering with the ongoing MRs, https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/commit/40b03f48b2537b57071e278c92d69d1eecdae992

**Comment by lesteve** [comment]
The new consensus (last bikeshedding on this):
- "Select a single answer"
- "Select all answers that apply"

I'll wait until the wrap-up quizzes MRs get merged and do everything in a single commit.

**Comment by lfarhi** [comment]
ok, "Select all answers that apply" is written below the questions for multiple-choice questions

**Comment by lesteve** [comment]
Done in gitlab and quizzes updated in github
