### ISSUE TITLE
Plotting in FUN sandbox has different format than notebooks

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#555]
Running Exercise M6.04 notebook on FUN yields the following boxplot:

![notebook](https://user-images.githubusercontent.com/86408019/151780887-e9b01654-b804-4cb7-b0b8-6b8f59a4fbf7.png)

Running the exact same code on the sandbox does not preserve the formatting:

![sandbox](https://user-images.githubusercontent.com/86408019/151780956-ba091b3d-22de-4075-85e0-c9f4178fa7dd.png)

The `patch_artist=True`and the `whis=1000` introduced in the `matplotlibrc` are missing.

**Comment by lesteve** [comment]
The `matplotlibrc` file is very likely missing, this should be in the `notebooks` folder. @brospars I think you probably need to add it as a file in the docker image.

**Comment by brospars** [comment]
Ok I'll do that.

**Comment by lesteve** [comment]
I misread @ArturoAmorQ top post, the `matplotlibrc` is used for the exercise notebook but not for sandbox notebook.

I think `matplotlibrc` needs to be added in the folder where the sandbox notebook lives. same thing for wrap-up quizz notebooks as well)

**Comment by lesteve** [comment]
Thanks, closing this one!
