### ISSUE TITLE
Add formatting to decimal output

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#556]
Related to #539.

As mentioned in [this forum comment](https://mooc-forums.inria.fr/moocsl/t/add-formatting-to-decimal-output/3666/4), we could add a `rc` file to have a consistent format for numerical data through the course.

**Comment by lesteve** [comment]
I looked a bit at this, it seems like the only way we may be able to do this is to create a IPython startup script (probably used by ipykernel too but I haven't tried ...) e.g. from [pandas doc](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html#setting-startup-options-in-python-ipython-environment)

And then maybe have an env variable to use our custom profile e.g. https://stackoverflow.com/questions/54890429/how-to-create-a-project-specific-startup-script-for-ipython

This does not seem very convenient, my personal feeling is that this issue not super-critical for v2.

**Comment by lesteve** [comment]
Let's close this, it seems to be too much complicated for too little gain ...
