### ISSUE TITLE
FUN need plotting.helpers in the notebooks folders

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#558]
We copy `python_scripts/helpers/plotting.py` in `notebooks` so that it can be used from the notebooks.

**Comment by lesteve** [comment]
Confirmed this is a problem: e.g. for this notebook
https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/courseware/4b434c675b7a4800920a1277b3240b52/e2cc2d51ac0341ca8449e4e23a5a44c9/

![image](https://user-images.githubusercontent.com/1680079/152144725-3a1c2911-a16b-45fc-9070-1f0322e806ec.png)

@brospars you need to copy `python_scripts/helpers/plotting.py` in all folders when there are notebooks.

Honestly it feels a lot easier to put all the wrap-up quiz + sandbox notebook (that's 7 notebooks) in the same folder, for this issue and https://github.com/INRIA/scikit-learn-mooc/issues/555.

**Comment by brospars** [comment]
I moved all notebooks to `/notebooks`and already changed the links in FUN

**Comment by lesteve** [comment]
Great! I think there is still some problem for `helpers.plotting`:

- I forgot but you very likely to copy `python_scripts/helpers/__init__.py` (i.e. the full folder `python_scripts/helpers`)
- `helpers` seems to be a html file rather than a folder:
 ![image](https://user-images.githubusercontent.com/1680079/152163261-888fd7b4-97a9-465a-879f-4d79feeebd8e.png)

**Comment by brospars** [comment]
Sorry I didn't double check ! Fixed !

**Comment by lesteve** [comment]
Thanks!
