### ISSUE TITLE
Issue on page /concluding_remarks.html

### ISSUE THREAD

**Issue by MarieCollin** [INRIA/scikit-learn-mooc#564]
Would it possible to include the short TOC "This course" with its 3 bullet points in a note so that it could be possible to ignore it in FUN ? 
We already include a detailed html TOC at the beginning of the concluding remarks page in FUN (like for the introduction page).

**Comment by MarieCollin** [comment]
The TOC is added automatically on FUN with the integration of the html page (not by hand).
There is only an other page on FUN with added TOC, the Introduction page: https://inria.github.io/scikit-learn-mooc/index.html

What I wanted to mention for the concluding_remarks page  is that it seems to me that the automatic TOC (either in FUN or in JupyterBook) and the beginning of the JupyterBook page (ie This course + 3 bullet points) are somehow redundant.
To me remove the automatic TOC in FUN or in the JupyterBook ?

**Comment by lesteve** [comment]
Hmmm this is how it looks in FUN 
![image](https://user-images.githubusercontent.com/1680079/153458240-63480344-e941-4f04-95da-891156ea96c5.png)

in part because I changed the title of the admonition, I think we should rely on the `?content_only` thing because the way you did it is way too fragile `admonition-the-last-course` is using the title of the admonition ...

```html
<div class="external-resource" data-hide="h1, .admonition-the-last-course, .topbar, .prev-next-area, .footer, .site-navigation, .headerlink, .remove-from-content-only" data-url="https://inria.github.io/scikit-learn-mooc/concluding_remarks.html?content_only">
```

**Comment by MarieCollin** [comment]
Thanks a lot ; that's perfect on the FUN side. 
In fact ‘?content_only‘ is not interpreted here (no javascript processing). I removed it here.

**Comment by lesteve** [comment]
OK at least remove `.admonition-the-last-course` which is definitely not needed, that will make me a little bit happier inside :wink:

**Comment by lesteve** [comment]
Great, thanks a lot :tada:!
