### ISSUE TITLE
Problem with sync quiz

### ISSUE THREAD

**Issue by lfarhi** [INRIA/scikit-learn-mooc#567]
https://inria.github.io/scikit-learn-mooc/linear_models/linear_models_wrap_up_quiz.html
Question "How large is the largest absolute value of the weight (coefficient) in this trained model?" --> answer is below !

**Comment by ogrisel** [comment]
Indeed there is a missing `+++  {"tags": ["solution"]}` separator. Let me fix this on the private repo and sync.

**Comment by ogrisel** [comment]
Pushed to master as e0f1901c544f8767bcb694ee637a22cd51d340b7, the online jupyter-book will update automatically in a few minutes.
