### ISSUE TITLE
Some pages do not have the "run icon" (rocket)

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#572]
On the following page:
https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_hands_on.html
the rocket is missing. I don't know why. When teaching with binder, it is an impediment.

**Comment by lesteve** [comment]
Weird ...

a possible work-around (for next time) is to point people to a Binder link with the generated full-index.md e.g. https://gke.mybinder.org/v2/gh/INRIA/scikit-learn-mooc/421b2b0?filepath=full-index.md and do the navigation inside Binder.

**Comment by GaelVaroquaux** [comment]
> a possible work-around (for next time) is to point people to a Binder link with the generated full-index.md e.g. https://gke.mybinder.org/v2/gh/INRIA/scikit-learn-mooc/421b2b0?filepath=full-index.md and do the navigation inside Binder.

I used a trick like this live, and thus things went quite smoothly. However, my thoughts were that:

1. teaching with the infrastructure is really amazing (I can picture teachers using this all across the world)

2. a little glitches like this could throw off balance a class

**Comment by lesteve** [comment]
Yep I definitely agree.

Looking at it in more details, it seems like the `.py` which shows the rocket icon have this kind of header at the beginning of the `.py` file:

```py
# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.6.0
#   kernelspec:
#     display_name: Python 3
```

Historically note:
- IIRC, these headers were added when converting the `.ipynb` with Jupytext
- I think they were needed at some point for the file to be considered notebook-like but I thought not any more, apparently this is a bit more complicated than that ...

**Comment by GaelVaroquaux** [comment]
Nice catch! There's probably too much information in this header, but it
might help to put it in every file.

**Comment by lesteve** [comment]
For the record I found https://github.com/executablebooks/jupyter-book/issues/646#issuecomment-636192692 and the reason seems to be that says:

> I think that the reason is because there is no front-matter for the notebook page at render time, and the launch buttons only show up if they find a `kernelspec` in the front matter.
