### ISSUE TITLE
The "Live Code" integration inserts the "Copy to clipboard" text inside the runnable cell

### ISSUE THREAD

**Issue by ogrisel** [INRIA/scikit-learn-mooc#575]
When using the rocket icon to start a live code session backend by mybinder.org:

![Screenshot 2022-02-15 at 11 26 46](https://user-images.githubusercontent.com/89061/154043562-c4ff7217-14ea-4a6f-8829-716af198ff6a.png)

then, in each code cell, the "Copy to clipboard" text is inserted. This causes a `IndentationError` / `SyntaxError` when running the cell as it's interpreted as being part of the Python code of the cell:

![Screenshot 2022-02-15 at 11 26 26](https://user-images.githubusercontent.com/89061/154043731-4841807f-eb2d-45fc-bc1b-776c86517223.png)

Related problem #572 (some notebooks, exercises or main notebooks, do not have the rocket icon to launch binder)

**Comment by lesteve** [comment]
This has been fixed in sphinx-thebe
