### ISSUE TITLE
Some units show "# -*- coding: utf-8 -*-" header - should it be removed?

### ISSUE THREAD

**Issue by miykael** [INRIA/scikit-learn-mooc#578]
It seems that ~28 units on the platform begin with `# -*- coding: utf-8 -*-`, see for example [this unit](https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models_ex_03.html), with the corresponding python script [here](https://github.com/INRIA/scikit-learn-mooc/blob/main/python_scripts/linear_models_ex_03.py#L8).

Running a quick `grep -lr "coding: utf-8" python_scripts | sort -h` reveals the issue to be present in the following scripts:

```
python_scripts/01_tabular_data_exploration_ex_01.py
python_scripts/02_numerical_pipeline_ex_00.py
python_scripts/02_numerical_pipeline_ex_01.py
python_scripts/03_categorical_pipeline_ex_01.py
python_scripts/03_categorical_pipeline_ex_02.py
python_scripts/03_categorical_pipeline_sol_02.py
python_scripts/cross_validation_ex_01.py
python_scripts/cross_validation_ex_02.py
python_scripts/cross_validation_sol_01.py
python_scripts/ensemble_ex_01.py
python_scripts/ensemble_ex_02.py
python_scripts/ensemble_ex_03.py
python_scripts/ensemble_ex_04.py
python_scripts/feature_selection_ex_01.py
python_scripts/linear_models_ex_01.py
python_scripts/linear_models_ex_02.py
python_scripts/linear_models_ex_03.py
python_scripts/linear_models_ex_04.py
python_scripts/linear_models_ex_05.py
python_scripts/linear_models_sol_01.py
python_scripts/linear_models_sol_02.py
python_scripts/metrics_ex_01.py
python_scripts/metrics_ex_02.py
python_scripts/parameter_tuning_ex_02.py
python_scripts/parameter_tuning_ex_03.py
python_scripts/trees_ex_01.py
python_scripts/trees_ex_02.py
python_scripts/trees_sol_01.py
```

I'm not sure if this source code encoding is needed for some functionalities. Otherwise, I'm also happy to create a quick PR and take care of them if that is desired.

**Comment by ogrisel** [comment]
I don't think it's needed. Feel free to do a PR.

**Comment by ogrisel** [comment]
It might be related to #408 that introduced the script to generate exercises from solutions. It might be a side effect of older versions of jupytext.

Please check that running `make exercises` does not re-add those lines.

**Comment by miykael** [comment]
Yes, `make exercises` would add them back in. However, the newest version of `jupytext`(7 days old) removed this flag with https://github.com/mwouts/jupytext/pull/915. So a simple update to `jupytext>=1.13.7` will do the trick (e.g. with `conda install -n scikit-learn-course 'jupytext>=1.13.7'`). Note, the [environment-dev.yml](https://github.com/INRIA/scikit-learn-mooc/blob/main/environment-dev.yml#L10) file is already setup correctly, so new users won't face that issue.
