### ISSUE TITLE
Issue on page /python_scripts/cross_validation_time.html (Non i.i.d. data)

### ISSUE THREAD

**Issue by naiborhujosua** [INRIA/scikit-learn-mooc#583]
I got an error NotADirectoryError: [Errno 20] Not a directory: '../datasets/financial-data/TOT.csv' while reading the CSV files. Maybe there is something wrong with the URL of the dataset. Where can I find the URL for the dataset?

```python
import pandas as pd

symbols = {"TOT": "Total", "XOM": "Exxon", "CVX": "Chevron",
           "COP": "ConocoPhillips", "VLO": "Valero Energy"}
template_name = ("../datasets/financial-data/{}.csv")

quotes = {}
for symbol in symbols:
    data = pd.read_csv(
        template_name.format(symbol), index_col=0, parse_dates=True
    )
    quotes[symbols[symbol]] = data["open"]
quotes = pd.DataFrame(quotes)
```

**Comment by ArturoAmorQ** [comment]
Thanks for reporting, @naiborhujosua. The problem was at FUN level but it is solved now (as mentioned in [this forum comment](https://mooc-forums.inria.fr/moocsl/t/non-i-i-d-data/7669/5)).
