### ISSUE TITLE
Two Question 10 in Wrap-up Quiz 7

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#619]
https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/courseware/cb3cfcaf0cae4cf7801c4e8d5dab9087/48227dd63e644389b15af316e6448536/#status_06d0881cc89e4cea94d0b8266329cfd6_2_1
![image](https://user-images.githubusercontent.com/1680079/162412350-4f047b43-61af-4514-89ee-913a52d06037.png)

Let's tackle this for session 3, since this will complicate analysis of quizz answers.

**Comment by ArturoAmorQ** [comment]
Done in FUN.
