### ISSUE TITLE
Social media icons not being correctly displayed on FUN

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#620]
### The rendering in [FUN](https://lms.fun-mooc.fr/courses/course-v1:inria+41026+session02/courseware/b59d1c0260ce40b28f145f4200780333/fe43500ef1c84d1b80d6a95d1ae8b275/):

![Screenshot from 2022-04-08 16-31-32](https://user-images.githubusercontent.com/86408019/162466006-0200441c-6982-4721-8d4c-cb3cb87c4ea4.png)

### The rendering in the [Jupyter Book](https://inria.github.io/scikit-learn-mooc/):

![Screenshot from 2022-04-08 16-39-19](https://user-images.githubusercontent.com/86408019/162466207-bb1b84a8-42b3-4e98-93e7-d158d8443954.png)

**Comment by ArturoAmorQ** [comment]
@brospars do you know if FUN can support fontawesome?

**Comment by ArturoAmorQ** [comment]
Is it possible to upgrade it to v5?

**Comment by brospars** [comment]
Not on our side and I doubt @openfun can do it easily

**Comment by GaelVaroquaux** [comment]
Can you use both tags (for both versions of fontawesome)?

**Comment by brospars** [comment]
It is now fixed.

**Comment by ArturoAmorQ** [comment]
Thank @brospars!

**Comment by GaelVaroquaux** [comment]
Can you show us the code? I think that you did something more clever that
I had in mind. I want to learn.

**Comment by brospars** [comment]
Fontawesome uses css classes and pseudo-elements to display an icon using a font. For example : 
```css
.fa {
  font: normal normal normal 14px/1 FontAwesome;
}

.fa-github::before {
  content: "\f09b";
}

...
```
So I simply added a rule in our custom css so that `.fab` is the same as `.fa` like so : 
```css
.fa, .fab{
  font: normal normal normal 14px/1 FontAwesome;
}

**Comment by GaelVaroquaux** [comment]
Yes, elegant!! Thanks
