### ISSUE TITLE
Exercise M4.04 demo of `LinearRegression` on repeated features is unstable

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#641]
Originally posted [here in the forum](https://mooc-forums.inria.fr/moocsl/t/different-outputs-for-linear-regression-coefficients/8000/3). Ridge regression with `alpha=1.0` leads to same result as the ordinary linear regression depending on the machine. This is possibly an Issue worth looking at from scikit-learn, but we may alternatively avoid this demo on the MOOC.

Reproducer from OP here: https://gist.github.com/qdpham/21b30181a8e0dd50cfcbba57b61e9b70

**Comment by ogrisel** [comment]
The problem is not with `Ridge` which always behaves as expected on both machines but rather that `LinearRegression` does not always fail as we expect it to fail depending on the machines.
