### ISSUE TITLE
How to cite this course/repo?

### ISSUE THREAD

**Issue by psteinb** [INRIA/scikit-learn-mooc#651]
In order to pay tribute to this fantastic content, I'd love to cite this repo or this course. It would be wonderful, if you could share in the `README.md` how to cite this.
Thanks in advance!

**Comment by lesteve** [comment]
Thanks for your kind words, it would be nice to add "how to cite this course" to the README indeed.

Having said that, I don't really know how other course repos manage this kind of thing. Suggestions more than welcome!

I am aware of this https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content but not sure we want to have a DOI for particular releases.

**Comment by psteinb** [comment]
I would encourage you to have DOIs ... for every release if possible.

**Comment by lesteve** [comment]
A few links I bumped into that may serve as data points:
- https://the-turing-way.netlify.app/welcome#citing-the-turing-way
- https://the-environmental-ds-book.netlify.app/preamble/attribution.html

For now we don't really do releases since the content is regularly evolving but we could if we think this is worth it (e.g. for each MOOC session) ...

**Comment by lesteve** [comment]
I followed the instructions in https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content. My understanding is that we need to create a github release for Zenodo to create automatically a DOI.

Remaining steps:
- do a github relase for the MOOC 3rd version
- add a small "how to cite us" section in `jupyter-book/index.md` similarly as in https://inria.github.io/scikit-learn-mooc/

**Comment by psteinb** [comment]
Great news! Thanks for making the effort. This will make it easier for us to cite this material.
