### ISSUE TITLE
Add Adult Census dataset description

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#657]
Currently the [Adult Census description](https://inria.github.io/scikit-learn-mooc/appendix/adult_census_description.html) contains only a redirection to the notebook [First look at our dataset](https://inria.github.io/scikit-learn-mooc/python_scripts/01_tabular_data_exploration.html), argumenting that it was already extensively explored in said notebook.

We can use the opportunity to give a deeper exploration of the data.

**Comment by ArturoAmorQ** [comment]
My idea is to add the following plots:

![1](https://user-images.githubusercontent.com/86408019/189114787-a4aa7c53-aedd-4e91-b056-f61e47e920fa.png)

![2](https://user-images.githubusercontent.com/86408019/189114801-c726502c-f37e-4c53-a9e4-139ab8ddd8eb.png)

![3](https://user-images.githubusercontent.com/86408019/189114816-f00f1794-8a52-4dc3-bddf-3cdac7231bea.png)

**Comment by lesteve** [comment]
My understanding from #659 is that it is in the "not worth it" category. Feel free to reopen if you disagree.

**Comment by ArturoAmorQ** [comment]
Re-opening in the spirit of #747.
