### ISSUE TITLE
[FEATURE REQUEST] Add CC-BY license to footer

### ISSUE THREAD

**Issue by darigovresearch** [INRIA/scikit-learn-mooc#681]
Thought it may be helpful to have the fact that the course is released under a CC-BY in the footer so it's visible on every page

For example:

Brought to you under a [CC-BY license](https://github.com/INRIA/scikit-learn-mooc/blob/main/LICENSE) by [Inria Learning Lab](https://learninglab.inria.fr/), [scikit-learn @ La Fondation Inria](https://scikit-learn.fondation-inria.fr/), [Inria Academy](https://www.inria-academy.fr/formation/scikit-learn-la-boite-a-outils-de-lapprentissage-automatique/), with many thanks to the [scikit-learn](https://scikit-learn.org/) community as a whole!

**Comment by lesteve** [comment]
See my comment in the associated PR: https://github.com/INRIA/scikit-learn-mooc/pull/682#issuecomment-1371871802

**Comment by lesteve** [comment]
We can close this one it was merged in #682

**Comment by darigovresearch** [comment]
@lesteve thanks for the help with this!
