### ISSUE TITLE
Reduce boilerplate

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#7]
Being didactic requires focusing on important things, and avoid side message.

The notebooks have too much boilerplate:

* calls to IPython.display
* mpl.rcParams
* plotting functions such as plot_tree_decision_function

I'm not quite sure what's the best way to address this problem. Maybe defining help functions in a modules could help?

**Comment by lesteve** [comment]
To me an approach like Andreas' one in his book with a library (he created [mglearn](https://github.com/amueller/mglearn) for this) to reduce the amount of code (e.g. plotting) makes sense. Here is an example:
![image](https://user-images.githubusercontent.com/1680079/84135826-bb9aaf00-aa4a-11ea-9b3a-158935af684c.png)
from this [notebook](https://github.com/amueller/introduction_to_ml_with_python/blob/master/02-supervised-learning.ipynb)

The devil is in the details and where you draw the bar, for me:
- mpl.rcParams at the top of the notebook with a comment saying this is for cosmetics is   borderline fine (you see what I mean hopefully)
- IPython.display hmmm not sure I would need to have an example but I would say borderline fine too ...

**Comment by GaelVaroquaux** [comment]
I indeed think that we can do a lot with a small module.

I disagree that mpl.rcParams is fine. But we can push some of these in the module. And in addition, they are usually details.

**Comment by GaelVaroquaux** [comment]
Also, we just should do less nitpicks in our code: some of these lines of code are not necessary.

**Comment by ogrisel** [comment]
Personally, I would rather avoid hiding too much magic in a sub module. But I agree there is a trade-off  with boiler plate.

**Comment by glemaitre** [comment]
Regarding the `plot_tree_decision_function` I think that we concluded that we wanted to remove the code and having a static image only and refer to outside code if people are interested to know how the figure was generated.

We are indeed not interested in the code there and having it is not didactic.

**Comment by lesteve** [comment]
Actually I am pretty sure I did it for the CDS workshop and never reintegrated it ... it was quite fragile though (not working reliably on binder IIRC or some other problems I don't remember exactly) so I would be enclined to use an external function instead ...

**Comment by GaelVaroquaux** [comment]
> Regarding the plot_tree_decision_function I think that we concluded that we
> wanted to remove the code and having a static image only and refer to outside
> code if people are interested to know how the figure was generated.

OK, so move it into the "figures" directory. Sounds good!

**Comment by lesteve** [comment]
Our comments probably crossed but I was saying that having an external figure caused problems (not 100% sure but maybe it was not visible in binder and nbviewer).

**Comment by glemaitre** [comment]
I am closing this issue since it is outdated for the specific comment.
We still have boilerplate but in other places :)
