### ISSUE TITLE
CSS for slides not robust enough?

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#73]
Thanks for having a look at this @GaelVaroquaux!

When I look at https://inria.github.io/scikit-learn-mooc/ml_concepts/slides.html, I get this:
![image](https://user-images.githubusercontent.com/1680079/97017357-16dac300-154e-11eb-9b39-6377b6901fc1.png)

- Is it only me?
- Does that mean that the CSS is not robust enough for different screen sizes?
- Is there a better way? There must be a better way, right?

**Comment by lesteve** [comment]
FWIW: on my laptop I do get something more reasonable:

![image](https://user-images.githubusercontent.com/1680079/97018682-b9e00c80-154f-11eb-932a-7a710e7e15cf.png)

**Comment by GaelVaroquaux** [comment]
Should be fixed.

**Comment by lesteve** [comment]
Works for me, thanks a lot!
