### ISSUE TITLE
Improvement once 0.24 is released

### ISSUE THREAD

**Issue by glemaitre** [INRIA/scikit-learn-mooc#74]
Once 0.24 is released, we should make the following improvement:

- [x] Use the MAPE whenever it makes sense.
- [x] Check again the plotting function using the new API.
- ~No need to specify in advance the categories in the `OrdinalEncoder` and use rare categories instead.~ We need to postpone such that `OneHotEncoder` support simple processing as well.
- [x] Add references to some scikit-learn example (interpretation of linear coefficient, common pitfalls, limitation of feature importances, etc.)

**Comment by lesteve** [comment]
> * ~No need to specify in advance the categories in the `OrdinalEncoder` and use rare categories instead.~ We need to postpone such that `OneHotEncoder` support simple processing as well.

@ogrisel says that maybe an option is to use `handle_unknown="ignore"` without `drop_binary`
