### ISSUE TITLE
Toggle navigation not working on pages with slide

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#75]
https://inria.github.io/scikit-learn-mooc/linear_models/slides.html

Clicking on "Toggle navigation" icon (left arrow on the top left):
![image](https://user-images.githubusercontent.com/1680079/97154381-1754a300-1774-11eb-806e-33f65a0bc793.png)

does not do anything. It does work on any other page I tried e.g.https://inria.github.io/scikit-learn-mooc/python_scripts/linear_models.html.

On the console:
```
Uncaught TypeError: $(...).tooltip is not a function
    initTooltips https://inria.github.io/scikit-learn-mooc/_static/sphinx-book-theme.be0a4a0c39cd630af62a2fcf693f3f06.js:8
    jQuery 9
    initTooltips https://inria.github.io/scikit-learn-mooc/_static/sphinx-book-theme.be0a4a0c39cd630af62a2fcf693f3f06.js:8
    sbRunWhenDOMLoaded https://inria.github.io/scikit-learn-mooc/_static/sphinx-book-theme.be0a4a0c39cd630af62a2fcf693f3f06.js:6
    <anonymous> https://inria.github.io/scikit-learn-mooc/_static/sphinx-book-theme.be0a4a0c39cd630af62a2fcf693f3f06.js:14
sphinx-book-theme.be0a4a0c39cd630af62a2fcf693f3f06.js:8:81
```

Maybe some conflict between the remark.js and the sphinx-book js?

Not so important, but in case someone has some suggestions.

**Comment by GaelVaroquaux** [comment]
> Maybe some conflict between the remark.js and the sphinx-book js?

Unlikely: remark is in an iframe. It should be isolated
