### ISSUE TITLE
Copyright remark from 2022

### ISSUE THREAD

**Issue by psteinb** [INRIA/scikit-learn-mooc#769]
I am currently teaching this material. I found that the copyright remark is dated 2022:

![image](https://github.com/INRIA/scikit-learn-mooc/assets/1465603/9255683d-6dd6-4313-b6ea-5af2db636b34)

I think, this should be changed.

**Comment by ArturoAmorQ** [comment]
Pinging @lesteve on this one (see https://github.com/INRIA/scikit-learn-mooc/issues/651 and https://github.com/INRIA/scikit-learn-mooc/pull/668 for historical context) for his advice on using the `session` tag or just modifying the text.

**Comment by lesteve** [comment]
The simpler the better, so update the text with 2024?

**Comment by ArturoAmorQ** [comment]
Then feel free to submit a PR, @psteinb :)
