### ISSUE TITLE
Every notebook should have a title

### ISSUE THREAD

**Issue by GaelVaroquaux** [INRIA/scikit-learn-mooc#9]
The title is useful to give an idea to the user of what is in there, and also for us to focus and stay on track

**Comment by lesteve** [comment]
:+1: adding subtitles where appropriate also

**Comment by GaelVaroquaux** [comment]
This seems fixed to me. Am I wrong?

**Comment by lesteve** [comment]
I think so. In any case the jupyter-book helps fixing this kind of problems.
