### ISSUE TITLE
Binary encoding of sex variable everywhere?

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#93]
This is done here: https://inria.github.io/scikit-learn-mooc/python_scripts/03_categorical_pipeline_column_transformer.html?highlight=binary_encoding_columns#columntransformer

but not here: 
https://inria.github.io/scikit-learn-mooc/python_scripts/04_parameter_tuning_search.html or probably in other places.

Need to search for ColumnTransformer to find where we define it.

**Comment by glemaitre** [comment]
What would be best if to use `drop="if_binary"` in `OneHotEncoder`. However, it conflicts with `handle_unknow="ignore"` but we might not need the latter option here?

I will check and make a Pull Request if applicable.

**Comment by glemaitre** [comment]
In 04_parameter_tuning_***, it seems that we are doing an OrdinalEncoder so we should be fine then?

**Comment by lesteve** [comment]
Good point so we want to only change the cases where we use a `ColumnTransformer` with a `OneHotEncoder`. From what I could grep, this only happens in `python_scripts/03_categorical_pipeline_sol_02.py`. We may want to adapt the exercise instructions as well in `python_scripts/03_categorical_pipeline_ex_02.py`.
