### ISSUE TITLE
Hypothesis usage

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#94]
Just a FYI I added hypothesis support in https://github.com/INRIA/scikit-learn-mooc/commit/56ae8b38925b94600ba7f3df66252ff04a001db0.

This may be useful to add quick notes/comments while reading the content without leaving the page. Not really sure how this would interact with github issues, we'll see.

If you select some text, you get some icons to annotate/highlight. Here is a screenshot:

![image](https://user-images.githubusercontent.com/1680079/99553238-3682d100-29be-11eb-9de0-1f11dee558e1.png)

You need to create an account at https://hypothes.is to be able to create annotations.

**Comment by lesteve** [comment]
You can then get a URL for annotations/highlight like this:
https://via.hypothes.is/https://inria.github.io/scikit-learn-mooc/python_scripts/03_categorical_pipeline_column_transformer.html?highlight=binary+encoding#annotations:ghlL5Cm0Eeufd1_7NzrbXg

**Comment by glemaitre** [comment]
I kinda got scared when I saw "hypothesis" :)
